function [model,file] = buildModel(c,options)
% BUILDMODEL  planar_visibility_v2 Simulink 학습·평가 모델 생성.
%
%   model = landing2d.simulink.buildModel(armConfig)
%   model = landing2d.simulink.buildModel(armConfig,struct('actionSource','player'))
%
% 최상위: RL Agent(또는 Action player) -> Action interface -> UGV landing
% environment -> 관측·보상·종료 -> RL Agent. 환경 안의 물리 블록은 0.01 s,
% 관측·보상은 0.1 s로 돌고, 각 블록은 기존 landing2d 함수를 그대로 부릅니다.
% 모델 파일은 생성물이므로 c.outputDir/models에 저장합니다.
if nargin < 2, options = struct(); end
defaults = struct('actionSource','agent','agentVariable','landing2dAgent', ...
    'name','','folder',fullfile(c.outputDir,'models'),'save',true);
options = mergeOptions(options,defaults);
assert(ismember(options.actionSource,{'agent','player'}), ...
    'landing2d:ActionSource','actionSource must be agent or player.');
mode = c.graphState.stateRepresentation;
e = c.experiment;
stateDim = policyStateDim(c);
model = options.name;
if isempty(model)
    model = sprintf('landing2d_%s',mode);
    if strcmp(options.actionSource,'player'), model = [model '_player']; end
end

% Simulink 캐시(.slxc)·빌드 폴더(slprj)가 MATLAB 현재 폴더(프로젝트 루트)에
% 생기지 않도록 모델 폴더 아래로 보냅니다.
cache = fullfile(options.folder,'cache');
if ~exist(cache,'dir'), mkdir(cache); end
Simulink.fileGenControl('set','CacheFolder',cache,'CodeGenFolder',cache);
if bdIsLoaded(model), close_system(model,0); end
% 이전에 생성한 같은 이름의 파일은 다시 만들 것이므로 지워서 이름 가림을 막습니다.
previous = fullfile(options.folder,[model '.slx']);
if options.save && isfile(previous), delete(previous); end
new_system(model);
set_param(model,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep',num2str(e.physicsDt,17), ...
    'StopTime',num2str(e.maxMissionTime+e.policyDt,17), ...
    'EnableMultiTasking','off','AutoInsertRateTranBlk','on', ...
    'SaveTime','off','SaveOutput','off','SaveState','off', ...
    'SignalLogging','off','ReturnWorkspaceOutputs','on');
set_param(model,'Description',sprintf(['UGV landing planar_visibility_v2, ' ...
    'state representation %s. Generated by landing2d.simulink.buildModel.'],mode));

ports = containers.Map();
policy = [model '/RL Agent'];
if strcmp(options.actionSource,'agent')
    add_block('rllib/RL Agent',policy,'Position',[40 120 180 220]);
    set_param(policy,'Agent',options.agentVariable);
else
    policy = [model '/Action player'];
    addSystem(policy,'landing2d.simulink.ActionPlayerBlock', ...
        struct('SampleTime',num2str(e.policyDt,17)),ports);
    set_param(policy,'Position',[40 140 180 200]);
end

actionInterface = [model '/Action interface'];
buildActionInterface(actionInterface,c);
set_param(actionInterface,'Position',[260 120 400 240]);

environment = [model '/UGV landing environment'];
buildEnvironment(environment,c,stateDim,ports);
set_param(environment,'Position',[480 110 680 250]);

stopBlock = [model '/Stop on isdone'];
add_block('simulink/Sinks/Stop Simulation',stopBlock,'Position',[780 260 820 300]);

connectPorts(model,policy,1,actionInterface,1,'u');
for k = 1:4
    names = {'aNorm','aRequest','decisionIndex','aNormPrevious'};
    connectPorts(model,actionInterface,k,environment,k,names{k});
end
if strcmp(options.actionSource,'agent')
    connectPorts(model,environment,1,policy,1,'observation');
    connectPorts(model,environment,2,policy,2,'reward');
    connectPorts(model,environment,3,policy,3,'isdone');
else
    sinkObservation = [model '/Observation sink'];
    sinkReward = [model '/Reward sink'];
    add_block('simulink/Sinks/Terminator',sinkObservation,'Position',[780 120 800 140]);
    add_block('simulink/Sinks/Terminator',sinkReward,'Position',[780 180 800 200]);
    connectPorts(model,environment,1,sinkObservation,1,'observation');
    connectPorts(model,environment,2,sinkReward,1,'reward');
end
connectPorts(model,environment,3,stopBlock,1,'isdone');
annotate(model,[40 20], ...
    ['planar_visibility_v2 closed loop. Agent decisions every ' ...
    num2str(e.policyDt) ' s; vehicle, UGV, camera noise, tracker, ' ...
    'supervisor and termination every ' num2str(e.physicsDt) ' s.']);

file = '';
if options.save
    if ~exist(options.folder,'dir'), mkdir(options.folder); end
    file = fullfile(options.folder,[model '.slx']);
    save_system(model,file);
end
end

% ---------------------------------------------------------------- 행동 연결부
function buildActionInterface(path,c)
add_block('simulink/Ports & Subsystems/Subsystem',path);
Simulink.SubSystem.deleteContents(path);
Td = num2str(c.experiment.policyDt,17);
add_block('simulink/Sources/In1',[path '/u'],'Position',[30 100 60 114]);
add_block('simulink/Math Operations/Trigonometric Function',[path '/tanh'], ...
    'Operator','tanh','Position',[110 90 160 124]);
add_block('simulink/Math Operations/Gain',[path '/Acceleration limits'], ...
    'Gain',sprintf('[%s;%s]',num2str(c.axMax,17),num2str(c.azMax,17)), ...
    'Multiplication','Element-wise(K.*u)','Position',[230 150 290 180]);
add_block('simulink/Sources/Constant',[path '/One'],'Value','1', ...
    'SampleTime',Td,'Position',[110 230 140 250]);
add_block('simulink/Math Operations/Sum',[path '/Decision counter'], ...
    'Inputs','++','Position',[230 230 260 260]);
add_block('simulink/Discrete/Unit Delay',[path '/Counter memory'], ...
    'InitialCondition','0','SampleTime',Td,'Position',[230 290 270 320], ...
    'Orientation','left');
add_block('simulink/Discrete/Unit Delay',[path '/Previous action'], ...
    'InitialCondition','[0;0]','SampleTime',Td,'Position',[230 340 270 370]);
outs = {'aNorm','aRequest','decisionIndex','aNormPrevious'};
y = [100 160 240 350];
for k = 1:numel(outs)
    add_block('simulink/Sinks/Out1',[path '/' outs{k}], ...
        'Position',[380 y(k) 410 y(k)+14]);
end
connectPorts(path,[path '/u'],1,[path '/tanh'],1,'u');
connectPorts(path,[path '/tanh'],1,[path '/aNorm'],1,'aNorm');
connectPorts(path,[path '/tanh'],1,[path '/Acceleration limits'],1,'');
connectPorts(path,[path '/tanh'],1,[path '/Previous action'],1,'');
connectPorts(path,[path '/Acceleration limits'],1,[path '/aRequest'],1,'aRequest');
connectPorts(path,[path '/One'],1,[path '/Decision counter'],1,'');
connectPorts(path,[path '/Counter memory'],1,[path '/Decision counter'],2,'');
connectPorts(path,[path '/Decision counter'],1,[path '/Counter memory'],1,'');
connectPorts(path,[path '/Decision counter'],1,[path '/decisionIndex'],1,'decisionIndex');
connectPorts(path,[path '/Previous action'],1,[path '/aNormPrevious'],1,'aNormPrevious');
end

% ------------------------------------------------------------------- 환경
function buildEnvironment(path,c,stateDim,ports)
add_block('simulink/Ports & Subsystems/Subsystem',path);
Simulink.SubSystem.deleteContents(path);
Ts = num2str(c.experiment.physicsDt,17);
Td = num2str(c.experiment.policyDt,17);
inputs = {'aNorm','aRequest','decisionIndex','aNormPrevious'};
for k = 1:numel(inputs)
    add_block('simulink/Sources/In1',[path '/' inputs{k}], ...
        'Position',[20 60*k 50 60*k+14]);
end
outputs = {'observation','reward','isdone'};
for k = 1:numel(outputs)
    add_block('simulink/Sinks/Out1',[path '/' outputs{k}], ...
        'Position',[1500 60*k 1530 60*k+14]);
end
fast = struct('SampleTime',Ts);
blocks = { ...
    'Episode state','EpisodeStateBlock',fast; ...
    'Decision latch','DecisionLatchBlock',fast; ...
    'Packet builder','PacketBuilderBlock',fast; ...
    'Safety supervisor','SafetySupervisorBlock',fast; ...
    'Drone dynamics','DroneDynamicsBlock',fast; ...
    'UGV trajectory','PadTrajectoryBlock',fast; ...
    'Contact check','TerminationBlock',fast; ...
    'Camera sensor','CameraSensorBlock',fast; ...
    'Pad tracker','PadTrackerBlock',fast; ...
    'Decision context','DecisionContextBlock',fast; ...
    'Termination check','TerminationBlock',fast; ...
    'Commit','CommitBlock',fast; ...
    'Decision output','DecisionOutputBlock', ...
        struct('SampleTime',Td,'StateDim',num2str(stateDim))};
for k = 1:size(blocks,1)
    addSystem([path '/' blocks{k,1}],['landing2d.simulink.' blocks{k,2}], ...
        blocks{k,3},ports);
    set_param([path '/' blocks{k,1}],'Position', ...
        [120+110*mod(k-1,6) 400+160*floor((k-1)/6) 200+110*mod(k-1,6) 520+160*floor((k-1)/6)]);
end
add_block('simulink/Sources/Constant',[path '/No prior event'], ...
    'Value',sprintf('zeros(%d,1)',landing2d.simulink.signalCodec('size','event')), ...
    'SampleTime','inf','Position',[120 300 170 330]);
scopes = {'Drone scope','UGV scope','Camera scope','Return scope'};
for k = 1:numel(scopes)
    add_block('simulink/Sinks/Scope',[path '/' scopes{k}], ...
        'Position',[1500 300+70*k 1540 340+70*k]);
end
% 에피소드 결과(마지막 값)를 SimulationOutput.episodeOutcome으로 돌려줍니다.
% 병렬 학습에서도 클라이언트가 커리큘럼 통계를 계산하는 경로입니다.
add_block('simulink/Sinks/To Workspace',[path '/Episode outcome log'], ...
    'VariableName','episodeOutcome','MaxDataPoints','1', ...
    'SaveFormat','Array','SampleTime',Td,'Position',[1500 680 1580 710]);

w = @(src,srcPort,dst,dstPort) wire(path,ports,src,srcPort,dst,dstPort);
% 확정 상태 분배
for d = {'Decision latch','Packet builder','Safety supervisor','Drone dynamics', ...
        'Contact check','Termination check','Commit','Decision output'}
    w('Episode state','drone',d{1},'drone');
end
for d = {'Decision latch','UGV trajectory','Contact check','Termination check', ...
        'Commit','Decision output'}
    w('Episode state','pad',d{1},'pad');
end
for d = {'Packet builder','Camera sensor','Decision output'}
    w('Episode state','measurement',d{1},'measurement');
end
for d = {'Packet builder','Pad tracker','Decision output'}
    w('Episode state','track',d{1},'track');
end
for name = {'status','clock','snapshot'}
    w('Episode state',name{1},'Decision latch',name{1});
    w('Episode state',name{1},'Decision output',name{1});
end
w('Episode state','drone','Drone scope',1);
w('Episode state','pad','UGV scope',1);
w('Episode state','measurement','Camera scope',1);
% 결정 경계와 행동
w('aNorm',1,'Decision latch','aNorm');
w('decisionIndex',1,'Decision latch','decisionIndex');
w('aRequest',1,'Safety supervisor','aRequest');
w('aNormPrevious',1,'Decision output','aNormPrevious');
w('Decision latch','status','Packet builder','status');
w('Decision latch','status','Contact check','status');
w('Decision latch','status','Decision context','status');
w('Decision latch','clock','Packet builder','clock');
w('Decision latch','clock','Commit','clock');
w('Decision latch','snapshot','Commit','snapshot');
for d = {'Drone dynamics','UGV trajectory','Contact check','Camera sensor', ...
        'Pad tracker','Decision context','Termination check','Commit'}
    w('Decision latch','timing',d{1},'timing');
end
% 감독기 -> 동역학
w('Packet builder','packet','Safety supervisor','packet');
w('Safety supervisor','aApplied','Drone dynamics','aApplied');
w('Safety supervisor','intervened','Commit','intervened');
for d = {'Contact check','Camera sensor','Pad tracker','Termination check','Commit'}
    w('Drone dynamics','droneNext',d{1},'droneNext');
end
w('Drone dynamics','hardViolation','Contact check','hardViolation');
w('Drone dynamics','hardViolation','Termination check','hardViolation');
for d = {'Contact check','Camera sensor','Termination check','Commit'}
    w('UGV trajectory','padNext',d{1},'padNext');
end
% 접촉 판정 -> 측정 -> 추정 -> 문맥 -> 종료 판정
w('No prior event',1,'Contact check','priorEvent');
w('Contact check','event','Camera sensor','event');
w('Contact check','event','Pad tracker','event');
w('Contact check','event','Decision context','event');
w('Contact check','event','Termination check','priorEvent');
w('Contact check','event','Commit','contactEvent');
w('Camera sensor','measurementNext','Pad tracker','measurementNext');
w('Camera sensor','measurementNext','Commit','measurementNext');
w('Pad tracker','trackNext','Decision context','trackNext');
w('Pad tracker','trackNext','Commit','trackNext');
w('Decision context','statusNext','Termination check','status');
w('Decision context','statusNext','Commit','statusNext');
w('Termination check','event','Commit','terminalEvent');
% 확정 -> 메모리
commitPorts = {'droneCommit','padCommit','measurementCommit','trackCommit', ...
    'statusCommit','clockCommit','snapshotCommit'};
memoryPorts = {'droneNext','padNext','measurementNext','trackNext', ...
    'statusNext','clockNext','snapshotNext'};
for k = 1:numel(commitPorts)
    w('Commit',commitPorts{k},'Episode state',memoryPorts{k});
end
% 결정 출력
w('Decision output','observation','observation',1);
w('Decision output','reward','reward',1);
w('Decision output','isdone','isdone',1);
w('Decision output','episodeReturn','Return scope',1);
w('Decision output','outcome','Episode outcome log',1);

groupBlocks(path,'Vehicle (supervisor + dynamics)', ...
    {'Safety supervisor','Drone dynamics'});
groupBlocks(path,'UGV pad',{'UGV trajectory'});
groupBlocks(path,'Perception (camera noise + tracker)', ...
    {'Camera sensor','Pad tracker'});
groupBlocks(path,'Mission logic',{'Decision latch','Packet builder', ...
    'Contact check','No prior event','Decision context', ...
    'Termination check','Commit'});
groupBlocks(path,'Episode memory',{'Episode state'});
groupBlocks(path,'Decision interface (policy rate)',{'Decision output'});
arrange(path);
end

% ------------------------------------------------------------------ 도우미
function addSystem(path,className,params,ports)
add_block('simulink/User-Defined Functions/MATLAB System',path);
set_param(path,'System',className);
set_param(path,'SimulateUsing','Interpreted execution');
names = fieldnames(params);
for i = 1:numel(names)
    set_param(path,names{i},params.(names{i}));
end
if ~isKey(ports,className)
    object = feval(className);
    ports(className) = struct('input',{object.portNames('input')}, ...
        'output',{object.portNames('output')});
end
end

function wire(system,ports,src,srcPort,dst,dstPort)
srcIndex = portIndex(system,ports,src,srcPort,'output');
dstIndex = portIndex(system,ports,dst,dstPort,'input');
name = '';
if ischar(srcPort), name = srcPort; end
connectPorts(system,[system '/' src],srcIndex,[system '/' dst],dstIndex,name);
end

function index = portIndex(system,ports,block,port,direction)
if isnumeric(port)
    index = port;
    return;
end
className = get_param([system '/' block],'System');
entry = ports(className);
index = find(strcmp(entry.(direction),port),1);
assert(~isempty(index),'landing2d:ModelPort','%s has no %s port %s.', ...
    block,direction,port);
end

function connectPorts(system,src,srcPort,dst,dstPort,name)
% 같은 출력 포트에서 여러 곳으로 갈 때도 add_line이 분기를 만듭니다.
srcName = relativeName(system,src);
dstName = relativeName(system,dst);
h = add_line(system,sprintf('%s/%d',srcName,srcPort), ...
    sprintf('%s/%d',dstName,dstPort),'autorouting','smart');
if ~isempty(name)
    set_param(h,'Name',name);
end
end

function name = relativeName(system,path)
prefix = [system '/'];
if strncmp(path,prefix,numel(prefix))
    name = path(numel(prefix)+1:end);
else
    name = path;
end
end

function groupBlocks(system,name,members)
handles = zeros(1,numel(members));
for i = 1:numel(members)
    handles(i) = get_param([system '/' members{i}],'Handle');
end
Simulink.BlockDiagram.createSubsystem(handles);
created = get_param(handles(1),'Parent');
set_param(created,'Name',name);
arrange([system '/' name]);
end

function arrange(system)
try
    Simulink.BlockDiagram.arrangeSystem(system);
catch
    % 자동 배치는 표시 전용입니다. 실패해도 모델 동작에는 영향이 없습니다.
end
end

function annotate(system,position,text)
note = Simulink.Annotation([system '/' text]);
note.Position = [position position+[600 20]];
end

function n = policyStateDim(c)
mode = c.graphState.stateRepresentation;
if strcmp(mode,'baseline')
    n = c.experiment.observationSchema.dimension;
else
    schema = landing2d.graphstate.contextSchema(mode);
    n = schema.inDim*schema.nNodes;
end
end

function options = mergeOptions(options,defaults)
names = fieldnames(options);
unknown = setdiff(names,fieldnames(defaults));
assert(isempty(unknown),'landing2d:UnknownOption', ...
    'Unknown buildModel option: %s',strjoin(unknown,', '));
for i = 1:numel(names), defaults.(names{i}) = options.(names{i}); end
options = defaults;
end
