function validateRlConfig(rl)
% VALIDATERLCONFIG  강화학습 설정 검증. 학습을 시작하기 전에 잘못된 값을 거부.
positiveInteger = {'actionInterval','hiddenSize','observationDim','actionDim', ...
    'bcEpisodes','bcEpochs','bcBatch','ppoIterations','episodesPerIteration', ...
    'ppoEpochs','miniBatch','evaluateEvery'};
for i = 1:numel(positiveInteger)
    validateattributes(rl.(positiveInteger{i}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,positiveInteger{i});
end
positive = {'captureWeight','distanceWeight','distanceScale','distanceExponent', ...
    'distanceRateScale','captureOutsideScale', ...
    'bcLearnRate','policyLearnRate', ...
    'valueLearnRate','clipRatio','maxGradNorm'};
for i = 1:numel(positive)
    validateattributes(rl.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(rl.seed,{'numeric'},{'scalar','real','finite','nonnegative','integer'});
validateattributes(rl.valueWarmup,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'valueWarmup');
if isfield(rl,'earlyStopPatience')
    validateattributes(rl.earlyStopPatience,{'numeric'}, ...
        {'scalar','real','finite','nonnegative','integer'},mfilename,'earlyStopPatience');
end
validateattributes(rl.initialOffsetFraction,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'initialOffsetFraction');
validateattributes(rl.parallelEpisodes,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'parallelEpisodes');
validateattributes(rl.parallelWorkers,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'parallelWorkers');
validateattributes(rl.curriculumFraction,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','<=',1},mfilename,'curriculumFraction');
validateattributes(rl.curriculumStartHeight,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'curriculumStartHeight');
validateattributes(rl.abortCurriculumFraction,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','<=',1},mfilename,'abortCurriculumFraction');
validateattributes(rl.abortCurriculumStart,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'abortCurriculumStart');
validateattributes(rl.motionCurriculumFraction,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','<=',1},mfilename,'motionCurriculumFraction');
validateattributes(rl.motionCurriculumStartScale,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',1},mfilename,'motionCurriculumStartScale');
assert(ischar(rl.curriculumMode) && isrow(rl.curriculumMode) ...
    && ismember(rl.curriculumMode,{'iteration','performance'}), ...
    'landing2d:CurriculumMode', ...
    'curriculumMode must be iteration or performance.');
validateattributes(rl.curriculumLandingThreshold,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',1},mfilename,'curriculumLandingThreshold');
validateattributes(rl.curriculumStep,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',1},mfilename,'curriculumStep');
validateattributes(rl.curriculumRequiredWindows,{'numeric'}, ...
    {'scalar','real','finite','positive','integer'}, ...
    mfilename,'curriculumRequiredWindows');
validateattributes(rl.curriculumFloorStartFraction,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<',1}, ...
    mfilename,'curriculumFloorStartFraction');
validateattributes(rl.curriculumFullDifficultyFraction,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',1}, ...
    mfilename,'curriculumFullDifficultyFraction');
assert(rl.curriculumFloorStartFraction < rl.curriculumFullDifficultyFraction, ...
    'landing2d:CurriculumSchedule', ...
    'curriculumFloorStartFraction must precede full difficulty.');
validateattributes(rl.checkpointMinCurriculum,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<=',1}, ...
    mfilename,'checkpointMinCurriculum');
validateattributes(rl.curriculumEasyReplayFraction,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<',1}, ...
    mfilename,'curriculumEasyReplayFraction');
validateattributes(rl.curriculumBridgeReplayFraction,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<',1}, ...
    mfilename,'curriculumBridgeReplayFraction');
assert(rl.curriculumEasyReplayFraction+rl.curriculumBridgeReplayFraction<1, ...
    'landing2d:CurriculumReplay', ...
    'Easy and bridge replay fractions must leave current-level episodes.');
validateattributes(rl.touchdownSpeedCurriculumScale,{'numeric'}, ...
    {'scalar','real','finite','>=',1}, ...
    mfilename,'touchdownSpeedCurriculumScale');
validateattributes(rl.unsafePenaltyCurriculumStart,{'numeric'}, ...
    {'scalar','real','finite','<',0},mfilename,'unsafePenaltyCurriculumStart');
validateattributes(rl.entropyWeight,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'entropyWeight');
validateattributes(rl.initialLogStd,{'numeric'}, ...
    {'scalar','real','finite'},mfilename,'initialLogStd');
validateattributes(rl.minimumLogStd,{'numeric'}, ...
    {'scalar','real','finite'},mfilename,'minimumLogStd');
assert(rl.minimumLogStd <= rl.initialLogStd, ...
    'rl.minimumLogStd must not exceed rl.initialLogStd.');
% 3D-option-only fields (landing2d.config.applySpatialDimension).
if isfield(rl,'lateralInitialLogStd')
    validateattributes(rl.lateralInitialLogStd,{'numeric'}, ...
        {'scalar','real','finite','>=',rl.minimumLogStd},mfilename,'lateralInitialLogStd');
end
if isfield(rl,'touchdownAttitudeCurriculumScale')
    validateattributes(rl.touchdownAttitudeCurriculumScale,{'numeric'}, ...
        {'scalar','real','finite','>=',1},mfilename,'touchdownAttitudeCurriculumScale');
end
if isfield(rl,'trackAuthorizationCurriculumScale')
    validateattributes(rl.trackAuthorizationCurriculumScale,{'numeric'}, ...
        {'scalar','real','finite','>=',1},mfilename,'trackAuthorizationCurriculumScale');
end
assert(rl.gamma > 0 && rl.gamma < 1,'rl.gamma must be in (0,1).');
assert(rl.lambda >= 0 && rl.lambda <= 1,'rl.lambda must be in [0,1].');
assert(rl.clipRatio < 1,'rl.clipRatio must be smaller than 1.');
assert(rl.observationDim >= 1, ...
    'rl.observationDim must be derived from the active named schema.');
assert(ismember(rl.actionDim,[2,3]), ...
    'rl.actionDim must be 2 ([a_x,a_z]) or 3 ([a_x,a_y,a_z], 3D option).');
validateattributes(rl.teacherNoise,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'teacherNoise');
ranges = {'initialHeightRange','initialOffsetRange','initialSpeedRange', ...
    'teacherHeightRange','curriculumStartT1Range'};
for i = 1:numel(ranges)
    value = rl.(ranges{i});
    validateattributes(value,{'numeric'},{'vector','real','finite','numel',2}, ...
        mfilename,ranges{i});
    assert(value(1) <= value(2),'%s must be increasing.',ranges{i});
end
assert(rl.initialHeightRange(1) > 0,'initialHeightRange must be positive.');
assert(rl.curriculumStartT1Range(1)>0, ...
    'curriculumStartT1Range must be positive.');
flags = {'useBehaviorClone','retrain','verbose'};
for i = 1:numel(flags)
    validateattributes(rl.(flags{i}),{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,flags{i});
end
assert(ischar(rl.distanceMode) && isrow(rl.distanceMode) ...
    && ismember(rl.distanceMode,{'hybrid','rate','proximity'}), ...
    'landing2d:UnknownDistanceMode', ...
    'rl.distanceMode must be hybrid, rate or proximity.');
assert(isscalar(rl.distanceRateShare) && isnumeric(rl.distanceRateShare) ...
    && rl.distanceRateShare >= 0 && rl.distanceRateShare <= 1, ...
    'rl.distanceRateShare must be in [0,1].');
assert(ischar(rl.captureMode) && isrow(rl.captureMode) ...
    && ismember(rl.captureMode,{'margin','binary'}), ...
    'landing2d:UnknownCaptureMode','rl.captureMode must be margin or binary.');
validateattributes(rl.captureBoundaryValue,{'numeric'}, ...
    {'scalar','real','finite','>',-1,'<',1},mfilename,'captureBoundaryValue');
assert(ischar(rl.policyFile) && isrow(rl.policyFile) && ~isempty(strtrim(rl.policyFile)), ...
    'rl.policyFile must be a nonempty character vector.');
% 교사 없이 학습할 때 덮어쓸 값들은 모두 기존 항목이어야 합니다.
assert(isstruct(rl.scratch) && isscalar(rl.scratch),'rl.scratch must be a scalar struct.');
keys = fieldnames(rl.scratch);
for i = 1:numel(keys)
    assert(isfield(rl,keys{i}),'landing2d:UnknownOption', ...
        'rl.scratch overrides an unknown option: %s',keys{i});
end
end
