function verifyCheckpointGraph(agent,c)
% VERIFYCHECKPOINTGRAPH  The stored typed graph must be the graph the configuration defines.
% The checkpoint keeps its own src/dst/type_id and graph_hash (encoderSpec.graph)
% and inference uses that stored topology. This check rebuilds the configured
% graph (same graph seed and perturbation) and rejects a checkpoint whose hash
% differs, so a canonical and a shuffled graph can never be swapped silently.
if ~isfield(agent,'encoderSpec') || ~isfield(agent.encoderSpec,'graph') ...
        || isempty(agent.encoderSpec.graph)
    return;
end
[~,spec] = landing2d.graphstate.encoderInit(c.graphState,c.rl.observationDim, ...
    RandStream('threefry','Seed',0));
assert(isfield(spec,'graph') && strcmp(spec.graph.hash,agent.encoderSpec.graph.hash) ...
    && isequal(spec.T.rel,agent.encoderSpec.T.rel), ...
    'landing2d:CheckpointGraph', ...
    'Checkpoint graph %s differs from the configured graph %s.', ...
    agent.encoderSpec.graph.hash,spec.graph.hash);
end
