function validateOntologyConfig(onto)
% VALIDATEONTOLOGYCONFIG  온톨로지/R-GAT 설정 검증.
positiveInteger = {'dataEpisodes','sampleStride','hiddenDim','relationDim', ...
    'epochs','batchSize','designRepeats','maxAttributionSamples', ...
    'sweepPoints','sweepIterations','sweepGrid'};
for i = 1:numel(positiveInteger)
    validateattributes(onto.(positiveInteger{i}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,positiveInteger{i});
end
positive = {'positionScale','alignScale','speedScale','padSpeedScale', ...
    'searchScale','initScale','learnRate','maxGradNorm','anchorWeight'};
for i = 1:numel(positive)
    validateattributes(onto.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(onto.seed,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'seed');
validateattributes(onto.importanceFloor,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'importanceFloor');
validateattributes(onto.outputRegularization,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'outputRegularization');
validateattributes(onto.noiseRange,{'numeric'}, ...
    {'vector','real','finite','positive','numel',2},mfilename,'noiseRange');
assert(onto.noiseRange(1) <= onto.noiseRange(2),'noiseRange must be increasing.');
validateattributes(onto.heightRange,{'numeric'}, ...
    {'vector','real','finite','positive','numel',2},mfilename,'heightRange');
assert(onto.heightRange(1) <= onto.heightRange(2),'heightRange must be increasing.');
assert(onto.labelGamma > 0 && onto.labelGamma <= 1,'labelGamma must be in (0,1].');
assert(onto.validationSplit >= 0 && onto.validationSplit < 1, ...
    'validationSplit must be in [0,1).');
schema = landing2d.ontology.nodeSchema();
nTerms = numel(schema.terms);
assert(ischar(onto.weightObjective) && isrow(onto.weightObjective) ...
    && ismember(onto.weightObjective,{'alignment','counterfactual','weightGraph'}), ...
    'landing2d:UnknownWeightObjective', ...
    'weightObjective must be alignment, counterfactual or weightGraph.');
validateattributes(onto.sweepShareRange,{'numeric'}, ...
    {'vector','real','finite','numel',2,'>',0,'<',1},mfilename,'sweepShareRange');
assert(onto.sweepShareRange(1) < onto.sweepShareRange(2), ...
    'sweepShareRange must be increasing.');
assert(ischar(onto.anchorTerm) && isrow(onto.anchorTerm) ...
    && ismember(onto.anchorTerm,{schema.terms.name}), ...
    'landing2d:UnknownAnchorTerm','anchorTerm must name one of the reward terms.');
assert(onto.weightMin >= 0 && onto.weightMax <= 1 && onto.weightMin < onto.weightMax, ...
    'Require 0 <= weightMin < weightMax <= 1.');
assert(nTerms*onto.weightMin <= 1 && nTerms*onto.weightMax >= 1, ...
    'landing2d:RewardWeightBounds', ...
    'weightMin/weightMax must contain a unit simplex for %d terms.',nTerms);
flags = {'redesign','verbose','sweepFromScratch'};
for i = 1:numel(flags)
    validateattributes(onto.(flags{i}),{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,flags{i});
end
assert(ischar(onto.designFile) && isrow(onto.designFile) ...
    && ~isempty(strtrim(onto.designFile)), ...
    'onto.designFile must be a nonempty character vector.');
end
