function adm = probeAdmissible(grid,p)
% PROBEADMISSIBLE  Precomputed admissible-set summary of probe P for the validity judge.
adm = struct('horizons',grid.horizons,'anySafe',grid.anySafe(:,p)', ...
    'fovActive',grid.fovActive(:,p)', ...
    'rules',struct('horizontalActive',grid.horizontalActive(p), ...
        'horizontalMetric',grid.horizontalMetric{p}, ...
        'verticalActive',grid.verticalActive(p)), ...
    'horizontalBest',grid.horizontalBest(:,p)','horizontalSpread',grid.horizontalSpread(:,p)', ...
    'verticalBest',grid.verticalBest(:,p)','verticalSpread',grid.verticalSpread(:,p)');
end
