function probe = probeRecord(bank,p)
% PROBERECORD  One fixed probe for the validity judge (evaluation-only fields).
% The decision/observation context is the reference-scale one, so validity is
% judged on the same physical situation and the same context for every scale.
ref = find(bank.meta.scales == bank.meta.referenceScale,1);
ctx = bank.context;
probe = struct('drone',bank.truth.drone(:,p),'pad',bank.truth.pad(:,p), ...
    'context',struct('visionUpdated',ctx.visionUpdated(p,ref), ...
        'estimateInitialized',ctx.estimateInitialized(p,ref), ...
        'visionAge',ctx.visionAge(p,ref), ...
        'landingInhibited',ctx.landingInhibited(p,ref), ...
        'abortRequested',ctx.abortRequested(p,ref), ...
        'finalDescentActive',ctx.finalDescentActive(p,ref)), ...
    'admissible',[]);
end
