function [env,observation,info] = reset(c,seed,options)
% RESET  Create independent scenario/sensor streams and a causal first packet.
if nargin < 2 || isempty(seed), seed = 1; end
if nargin < 3, options = struct(); end
assert(isfield(c,'experiment') && c.experiment.enabled, ...
    'landing2d:ExperimentVersion','reset requires planar_visibility_v2.');
base = c.experiment.scenario.baseSeed+double(seed);
scenarioSeed = base+c.experiment.randomStreams.scenarioOffset;
sensorSeed = base+c.experiment.randomStreams.sensorOffset;
scenario = landing2d.scenario.sampleParameters(c.experiment.scenario,scenarioSeed);
if isfield(options,'scenario'), scenario = options.scenario; end
c.experiment.currentScenario = scenario;
sensorStream = RandStream('threefry','Seed',sensorSeed);
sensorEvents = landing2d.sensing.sampleEvents(c.experiment.sensor,scenario,sensorStream);
[padX,padVx,padAx,phase] = landing2d.scenario.evaluateTrajectory(scenario,0);
pad = struct('x',padX,'z',scenario.padHeight,'vx',padVx,'ax',padAx, ...
    'phase',phase);
state = struct('x',scenario.x0,'z',scenario.padHeight+scenario.height, ...
    'vx',0,'vz',0,'theta',0,'pitchRate',0, ...
    'collectiveThrust',c.experiment.dynamics.mass* ...
        c.experiment.dynamics.gravity);
if isfield(options,'physicalState'), state = options.physicalState; end
status = landing2d.environment.initialStatus();
track = landing2d.sensing.initialPadTrack(c.experiment.sensor);
measurement = landing2d.sensing.generateMeasurement(state,pad,0, ...
    c.experiment.sensor,sensorStream,struct('dropout',false));
[track,estimatorInfo] = landing2d.sensing.updatePadTrack(track,measurement, ...
    state,0,c.experiment.sensor);
status = landing2d.environment.updateDecisionContext(status,track,0,c);
packet = landing2d.sensing.buildPacket(state,track,measurement,status,scenario,0,c);
observation = landing2d.sensing.normalizePacket(packet,c);
env = struct('schemaVersion','environment_v2','config',c,'scenario',scenario, ...
    'physicalState',state,'observationMemory',track, ...
    'decisionContext',status,'episodeStatus',status,'time',0, ...
    'pad',pad,'measurement',measurement,'packet',packet, ...
    'sensorStream',sensorStream,'sensorEvents',sensorEvents, ...
    'stepCount',0,'rewardSum',0);
info = struct('packet',packet,'measurement',measurement,'pad',pad, ...
    'scenario',scenario,'estimator',estimatorInfo, ...
    'evaluatorMetadata',struct('sensorEvents',sensorEvents), ...
    'provenance',struct('scenarioSeed',scenarioSeed,'sensorSeed',sensorSeed, ...
    'policySeed',base+c.experiment.randomStreams.policyOffset));
end
