function validateRlConfig(rl)
% VALIDATERLCONFIG  강화학습 설정 검증. 학습을 시작하기 전에 잘못된 값을 거부.
positiveInteger = {'actionInterval','hiddenSize','observationDim','actionDim', ...
    'bcEpisodes','bcEpochs','bcBatch','ppoIterations','episodesPerIteration', ...
    'ppoEpochs','miniBatch','evaluateEvery'};
for i = 1:numel(positiveInteger)
    validateattributes(rl.(positiveInteger{i}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,positiveInteger{i});
end
positive = {'captureWeight','distanceWeight','distanceScale','distanceExponent', ...
    'distanceRateScale', ...
    'bcLearnRate','policyLearnRate', ...
    'valueLearnRate','clipRatio','maxGradNorm'};
for i = 1:numel(positive)
    validateattributes(rl.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(rl.seed,{'numeric'},{'scalar','real','finite','nonnegative','integer'});
validateattributes(rl.valueWarmup,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'valueWarmup');
if isfield(rl,'earlyStopPatience')
    validateattributes(rl.earlyStopPatience,{'numeric'}, ...
        {'scalar','real','finite','nonnegative','integer'},mfilename,'earlyStopPatience');
end
validateattributes(rl.initialOffsetFraction,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'initialOffsetFraction');
validateattributes(rl.parallelEpisodes,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'parallelEpisodes');
validateattributes(rl.parallelWorkers,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'parallelWorkers');
validateattributes(rl.curriculumFraction,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','<=',1},mfilename,'curriculumFraction');
validateattributes(rl.curriculumStartHeight,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'curriculumStartHeight');
validateattributes(rl.entropyWeight,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'entropyWeight');
validateattributes(rl.initialLogStd,{'numeric'}, ...
    {'scalar','real','finite'},mfilename,'initialLogStd');
assert(rl.gamma > 0 && rl.gamma < 1,'rl.gamma must be in (0,1).');
assert(rl.lambda >= 0 && rl.lambda <= 1,'rl.lambda must be in [0,1].');
assert(rl.clipRatio < 1,'rl.clipRatio must be smaller than 1.');
assert(rl.observationDim == 11,'rl.observationDim must match landing2d.rl.observation.');
assert(rl.actionDim == 2,'rl.actionDim must be 2: horizontal and vertical command.');
validateattributes(rl.teacherNoise,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'teacherNoise');
ranges = {'initialHeightRange','initialOffsetRange','initialSpeedRange', ...
    'teacherHeightRange'};
for i = 1:numel(ranges)
    value = rl.(ranges{i});
    validateattributes(value,{'numeric'},{'vector','real','finite','numel',2}, ...
        mfilename,ranges{i});
    assert(value(1) <= value(2),'%s must be increasing.',ranges{i});
end
assert(rl.initialHeightRange(1) > 0,'initialHeightRange must be positive.');
flags = {'useBehaviorClone','retrain','verbose'};
for i = 1:numel(flags)
    validateattributes(rl.(flags{i}),{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,flags{i});
end
assert(ischar(rl.distanceMode) && isrow(rl.distanceMode) ...
    && ismember(rl.distanceMode,{'hybrid','rate','proximity'}), ...
    'landing2d:UnknownDistanceMode', ...
    'rl.distanceMode must be hybrid, rate or proximity.');
assert(isscalar(rl.distanceRateShare) && isnumeric(rl.distanceRateShare) ...
    && rl.distanceRateShare >= 0 && rl.distanceRateShare <= 1, ...
    'rl.distanceRateShare must be in [0,1].');
assert(ischar(rl.captureMode) && isrow(rl.captureMode) ...
    && ismember(rl.captureMode,{'margin','binary'}), ...
    'landing2d:UnknownCaptureMode','rl.captureMode must be margin or binary.');
assert(ischar(rl.policyFile) && isrow(rl.policyFile) && ~isempty(strtrim(rl.policyFile)), ...
    'rl.policyFile must be a nonempty character vector.');
% 교사 없이 학습할 때 덮어쓸 값들은 모두 기존 항목이어야 합니다.
assert(isstruct(rl.scratch) && isscalar(rl.scratch),'rl.scratch must be a scalar struct.');
keys = fieldnames(rl.scratch);
for i = 1:numel(keys)
    assert(isfield(rl,keys{i}),'landing2d:UnknownOption', ...
        'rl.scratch overrides an unknown option: %s',keys{i});
end
end
