function status = initialStatus()
% INITIALSTATUS  Episode flags kept separate from physical and estimator state.
status = struct('terminated',false,'truncated',false,'terminalReason','', ...
    'terminalRewardPaid',false,'landingInhibited',true, ...
    'abortRequested',false,'abortRequestTime',NaN,'abortCompletionTime',NaN, ...
    'previousNormalizedAction',[0;0],'supervisorDuration',0, ...
    'physicalContact',false,'contactAuthorized',false, ...
    'mechanicallySafeContact',false,'contact',struct());
end
