function id = taskFingerprint(c)
% TASKFINGERPRINT  Method-independent environment/reward/safety contract hash.
contract = struct('schemaVersion',c.experiment.schemaVersion, ...
    'timing',[c.experiment.physicsDt,c.experiment.policyDt], ...
    'scenario',c.experiment.scenario,'dynamics',c.experiment.dynamics, ...
    'sensor',c.experiment.sensor,'safety',c.experiment.safety, ...
    'reward',c.experiment.reward,'actionLimits',[c.axMax,c.azMax], ...
    'observationSchema',c.experiment.observationSchema.version);
text=jsonencode(contract);
id=landing2d.util.checksum(double(unicode2native(text,'UTF-8')));
end
