function [schema,T] = contextSchema(mode,dimension)
% CONTEXTSCHEMA  Compact typed ontology used by planar_visibility_v2.
% dimension=3 (3D option) keeps the nodes and relations and appends two
% lateral feature channels before the three static channels.
if nargin < 1, mode = 'context_rgat'; end
if nargin < 2 || isempty(dimension), dimension = 2; end
assert(ismember(dimension,[2,3]),'landing2d:SpatialDimension', ...
    'contextSchema supports dimension 2 or 3.');
semantic = {'PadVisibility','PadMotion','DroneTranslation','DroneAttitude', ...
    'RelativeTracking','TrackingCorrection','ViewRecovery', ...
    'DescentEligibility','LandingInhibit'};
schema.nodeNames = semantic;
schema.nNodes = numel(schema.nodeNames);
schema.ontologyNodes = 1:numel(semantic);
schema.nodeClasses = {'ObservationState','MotionEstimate','OwnState', ...
    'OwnState','RelativeState','DecisionContext','DecisionContext', ...
    'DecisionContext','DecisionContext'};
schema.relationNames = {'informs','affects_visibility','supports', ...
    'inhibits','self'};
schema.nRelations = numel(schema.relationNames);
edges = { ...
    'PadMotion','RelativeTracking','informs'; ...
    'DroneTranslation','RelativeTracking','informs'; ...
    'DroneAttitude','PadVisibility','affects_visibility'; ...
    'DroneTranslation','PadVisibility','affects_visibility'; ...
    'PadMotion','TrackingCorrection','informs'; ...
    'RelativeTracking','TrackingCorrection','informs'; ...
    'PadVisibility','ViewRecovery','informs'; ...
    'DroneAttitude','ViewRecovery','informs'; ...
    'RelativeTracking','ViewRecovery','informs'; ...
    'PadVisibility','DescentEligibility','supports'; ...
    'RelativeTracking','DescentEligibility','informs'; ...
    'DroneTranslation','DescentEligibility','informs'; ...
    'DroneAttitude','DescentEligibility','informs'; ...
    'PadVisibility','LandingInhibit','informs'; ...
    'RelativeTracking','LandingInhibit','informs'; ...
    'DroneTranslation','LandingInhibit','informs'; ...
    'LandingInhibit','DescentEligibility','inhibits'};
src = zeros(1,size(edges,1)); dst = src; rel = src;
for i = 1:size(edges,1)
    src(i) = find(strcmp(schema.nodeNames,edges{i,1}));
    dst(i) = find(strcmp(schema.nodeNames,edges{i,2}));
    rel(i) = find(strcmp(schema.relationNames,edges{i,3}));
end
self = find(strcmp(schema.relationNames,'self'));
src = [src,1:schema.nNodes];
dst = [dst,1:schema.nNodes];
rel = [rel,self*ones(1,schema.nNodes)];
if strcmp(mode,'context_gat')
    rel(:) = 1;
    schema.relationNames = {'adjacent'};
    schema.nRelations = 1;
elseif ~ismember(mode,{'context_rgat','context_flat','context_node_pool'})
    error('landing2d:ContextMode','Unknown context graph mode %s.',mode);
end
schema.src = src; schema.dst = dst; schema.rel = rel;
schema.featureNames = {'primary','signedPrimary','secondary', ...
    'signedSecondary','validity','confidence','uncertainty','trend', ...
    'urgency','remainingTime','bias','typeId'};
if dimension == 3
    schema.featureNames = [schema.featureNames(1:9), ...
        {'lateralPrimary','lateralSecondary'},schema.featureNames(10:12)];
end
schema.inDim = numel(schema.featureNames);
schema.neutralValue = zeros(1,schema.nNodes);
schema.riskNodes = [7,9];
schema.goalNode = 8;
schema.groupNames = {'Perception','Tracking','Vehicle','Safety'};
schema.readoutGroups = {[1,7],[2,5,6],[3,4],[8,9]};
schema.groupMatrix = zeros(numel(schema.readoutGroups),schema.nNodes);
for g = 1:numel(schema.readoutGroups)
    nodes = schema.readoutGroups{g};
    schema.groupMatrix(g,nodes) = 1/numel(nodes);
end
schema.variant = 'compact_context_graph_v3_grouped';
if dimension == 3
    schema.variant = 'compact_context_graph_v3_grouped_spatial';
    schema.spatialDimension = 3;
end
schema.edgeTable = edges;
schema.provenance = featureProvenance();
if nargout > 1, T = landing2d.rgat.topology(schema); end
end

function p = featureProvenance()
p = struct( ...
    'PadVisibility','packet visibility measurements and predicted bearing', ...
    'PadMotion','shared causal pad track estimate and uncertainty', ...
    'DroneTranslation','synchronized own h/vx/vz', ...
    'DroneAttitude','synchronized own sin/cos pitch and pitch rate', ...
    'RelativeTracking','estimated signed ex/relative vx and uncertainty', ...
    'TrackingCorrection','bounded signed correction context from relative estimates', ...
    'ViewRecovery','predicted bearing/FOV margin and detection age', ...
    'DescentEligibility','bounded causal alignment/confidence/braking evidence', ...
    'LandingInhibit','public inhibit/abort flags and causal uncertainty');
end
