function validateGraphStateConfig(gs)
% VALIDATEGRAPHSTATECONFIG  상태 표현 설정 검증.
modes = {'baseline','semantic_flat','node_pool','gat','ontology_rgat', ...
    'context_flat','context_node_pool','context_gat','context_rgat'};
assert(ischar(gs.stateRepresentation) && isrow(gs.stateRepresentation) ...
    && ismember(gs.stateRepresentation,modes), ...
    'landing2d:UnknownStateRepresentation', ...
    'graphState.stateRepresentation must be one of: %s.',strjoin(modes,', '));
assert(ischar(gs.readout) && isrow(gs.readout) ...
    && ismember(gs.readout,{'decision_nodes','meanmax','mean','grouped', ...
    'raw_plus_groups'}), ...
    'landing2d:UnknownReadout', ...
    'graphState.readout must be decision_nodes, meanmax, or mean.');
positiveInteger = {'hiddenDim','relationDim','graphDim'};
for i = 1:numel(positiveInteger)
    validateattributes(gs.(positiveInteger{i}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,positiveInteger{i});
end
positive = {'initScale','encoderLearnRate','positionScale','distanceScale', ...
    'alignScale','speedScale','searchScale','padSpeedScale'};
for i = 1:numel(positive)
    validateattributes(gs.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(gs.useScratchSettings,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'useScratchSettings');
validateattributes(gs.freezeStaticBackbone,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'freezeStaticBackbone');
validateattributes(gs.graphAdaptationWarmupFraction,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<',1}, ...
    mfilename,'graphAdaptationWarmupFraction');
validateattributes(gs.preserveRawPolicyDuringGraphAdaptation, ...
    {'logical','numeric'},{'scalar','real','finite','binary'}, ...
    mfilename,'preserveRawPolicyDuringGraphAdaptation');
validateattributes(gs.graphSelectionMargin,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'graphSelectionMargin');
assert(isstruct(gs.pretrain) && isscalar(gs.pretrain), ...
    'graphState.pretrain must be a scalar struct.');
validateattributes(gs.pretrain.enabled,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'pretrain.enabled');
for name = {'episodes','maxDecisions','epochs','batchSize'}
    validateattributes(gs.pretrain.(name{1}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,name{1});
end
validateattributes(gs.pretrain.seedOffset,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'seedOffset');
validateattributes(gs.pretrain.maskProbability,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<',1},mfilename,'pretrain.maskProbability');
validateattributes(gs.pretrain.learnRate,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'pretrain.learnRate');
% 평면 계약의 그래프 원천. 없으면 causal packet (3차원 옵션·구 설정).
if isfield(gs,'observationSource')
    assert(ismember(gs.observationSource,{'packet','commonObservation'}), ...
        'landing2d:GraphObservationSource', ...
        'graphState.observationSource must be packet or commonObservation.');
end
% 공통 관측 그래프의 노드 특징 버전 (평면 계약 전용).
if isfield(gs,'observationFeatures')
    assert(isfield(gs,'observationSource') ...
        && strcmp(gs.observationSource,'commonObservation') ...
        && ismember(gs.observationFeatures,{'forward_camera_v2','minimal_sensor_v1'}), ...
        'landing2d:GraphObservationFeatures', ...
        'graphState.observationFeatures must name a registered common-observation graph.');
end
% raw semantic bypass의 MLP 입력 표준화 여부 (평면 계약 전용, 없으면 표준화).
if isfield(gs,'standardizeRawBypass')
    assert(islogical(gs.standardizeRawBypass) && isscalar(gs.standardizeRawBypass) ...
        && isfield(gs,'observationFeatures'),'landing2d:StandardizeRawBypass', ...
        'graphState.standardizeRawBypass must be a logical scalar of the planar contract.');
end
% 관계 교란 비교군에서만 존재하는 항목 (없으면 정준 관계 배치).
if isfield(gs,'relationPerturbation')
    p = gs.relationPerturbation;
    assert(isstruct(p) && isscalar(p) && strcmp(p.type,'edge_relation_shuffle'), ...
        'landing2d:RelationPerturbation', ...
        'graphState.relationPerturbation.type must be edge_relation_shuffle.');
    validateattributes(p.graphSeed,{'numeric'},{'scalar','integer','positive'}, ...
        mfilename,'relationPerturbation.graphSeed');
    assert(strcmp(gs.stateRepresentation,'context_rgat'), ...
        'landing2d:RelationPerturbation', ...
        'Relation shuffles apply to the typed context_rgat graph only.');
end
% 3차원 옵션에서만 존재하는 항목. 2차원 설정에는 넣지 않아 기존 서명을 유지합니다.
if isfield(gs,'spatialDimension')
    assert(isequal(gs.spatialDimension,3),'landing2d:SpatialDimension', ...
        'graphState.spatialDimension exists only for the 3D option and must be 3.');
end
assert(ischar(gs.policyFile) && isrow(gs.policyFile) ...
    && ~isempty(strtrim(gs.policyFile)), ...
    'graphState.policyFile must be a nonempty character vector.');
end
