function logTable = resultToTable(r,c)
% RESULTTOTABLE  저장용 시간 로그. 속도 구간 번호와 제어 입력도 포함.
segmentId = landing2d.scenario.segmentIndex(r.time,c.segmentTimes);
logTable = table(r.time,segmentId,r.xUgv,r.zPad,r.vxUgv,r.vxUgvCommand, ...
    r.xDrone,r.zDrone,r.vxDrone,r.vzDrone,r.xError,r.fovHalfWidth, ...
    r.visible,r.mode,r.descending,r.axCommand,r.azCommand,r.heightReference, ...
    'VariableNames',{'Time_s','SpeedSegment','UgvX_m','PadZ_m', ...
    'UgvVx_mps','UgvVxCommand_mps','DroneX_m','DroneZ_m','DroneVx_mps', ...
    'DroneVz_mps','XError_m','FovHalfWidth_m','PadVisible','Mode','Descending', ...
    'AxCommand_mps2','AzCommand_mps2','HeightReferenceAbovePad_m'});
end
