function styles = eventStyles()
% EVENTSTYLES  두 그래프에서 같은 의미로 쓰는 사건 표시 규칙.
% 사건 색/기호는 제어기와 무관하게 고정하고, 제어기 구분은 선 색/선형으로 합니다.
styles = struct( ...
    'field',{'lossTimes','reacquireTimes','landingTime','failureTime'}, ...
    'marker',{'x','s','v','v'}, ...
    'color',{[0.72,0.20,0.20],[0.13,0.45,0.30],[0.12,0.12,0.12],[0.72,0.20,0.20]}, ...
    'label',{'FOV loss','Reacquired','Landed','Failed'}, ...
    'faceColor',{'none','w','w','none'});
end
