function assertCausalPacket(packet)
% ASSERTCAUSALPACKET Reject labels, future values, and hidden simulator truth.
% The context graph may use only the synchronized online packet. Previous
% actions are causal packet members but are deliberately not read by
% contextGraph, keeping all compared state representations action-free.
persistent validatedNames
names = fieldnames(packet)';
if ~isempty(validatedNames) && isequal(names,validatedNames)
    return;
end
allowed = {'h','vx','vz','sinTheta','cosTheta','pitchRate', ...
    'exEstimate','relativeVxEstimate','padVxEstimate','padAxEstimate', ...
    'positionStd','velocityStd','accelerationStd','trackInitialized', ...
    'detected','measuredBearing','bearingValid','detectionConfidence', ...
    'timeSinceLastDetection','predictedBearing','predictedFovMargin', ...
    'remainingMissionTime','previousNormalizedActionX', ...
    'previousNormalizedActionZ','landingInhibited','abortRequested'};
unknown = setdiff(names,allowed);
assert(isempty(unknown),'landing2d:InformationLeakage', ...
    'Context packet contains non-causal or unregistered fields: %s', ...
    strjoin(unknown,', '));
required = setdiff(allowed,{'previousNormalizedActionX', ...
    'previousNormalizedActionZ'});
missing = setdiff(required,names);
assert(isempty(missing),'landing2d:CausalPacketSchema', ...
    'Context packet is missing required causal fields: %s',strjoin(missing,', '));
validatedNames = names;
end
