function [results,info] = evaluatePnV2(c,seeds)
% EVALUATEPNV2  Paired held-out V2 evaluation for the causal PN comparator.
cells=cell(1,numel(seeds)); returns=zeros(1,numel(seeds));
success=false(size(returns)); unsafe=success; abort=success; capture=zeros(size(returns));
timeout=success;
for i=1:numel(seeds)
    cells{i}=landing2d.control.rolloutPnV2(c,seeds(i));
    returns(i)=cells{i}.return; capture(i)=cells{i}.captureRate;
    reason=cells{i}.terminalReason;
    success(i)=strcmp(reason,'SUCCESS');
    unsafe(i)=ismember(reason,{'UNSAFE_CONTACT','UNAUTHORIZED_CONTACT', ...
        'MISSED_PAD_CONTACT','SAFETY_ENVELOPE_VIOLATION'});
    abort(i)=strcmp(reason,'SAFE_ABORT');
    timeout(i)=strcmp(reason,'TASK_TIMEOUT');
end
results=[cells{:}];
[selectionScore,outcomeRates]=landing2d.rl.selectionScoreV2( ...
    {results.terminalReason},returns);
info=struct('returns',returns,'captureRate',capture,'landed',success, ...
    'landingTime',[results.landingTime],'landingRate',mean(success), ...
    'meanCaptureRate',mean(capture),'meanReturn',mean(returns), ...
    'selectionScore',selectionScore, ...
    'unsafeRate',mean(unsafe),'safeAbortRate',mean(abort), ...
    'timeoutRate',mean(timeout),'outcomeRates',outcomeRates, ...
    'nodeMean',[],'nodeVariance',[],'edgeAttentionMean',[],'graphSchema',struct());
end
