function v2 = defaultPlanarVisibilityConfig()
% DEFAULTPLANARVISIBILITYCONFIG  Versioned contract for the primary experiment.
% Values are simulation starting points, not identified vehicle parameters.
v2.schemaVersion = 'planar_visibility_v2';
v2.enabled = true;
v2.legacyDynamics = false;
v2.physicsDt = 0.01;
v2.policyDt = 0.10;
v2.maxMissionTime = 70;

v2.dynamics = struct( ...
    'mass',1.5,'gravity',9.81, ...
    'pitchLimit',deg2rad(20),'pitchRateLimit',deg2rad(90), ...
    'pitchNaturalFrequency',10,'pitchDampingRatio',1, ...
    'thrustTimeConstant',0.05,'maxThrustWeightRatio',1.6, ...
    'pitchDisturbanceLimit',deg2rad(2));

v2.scenario = struct( ...
    'parameterization','duration','v1Range',[0.5,2.5], ...
    'a2Range',[0.3,1.5],'T1Range',[0.5,4], ...
    'T2Range',[0.5,4],'T3Range',[15,55], ...
    'heightRange',[4,8],'x0',0,'padHeight',0.6, ...
    'sustainedDroneSpeed',10,'speedMargin',0.5, ...
    'baseSeed',20261002,'maxRejections',1000);

% One physical camera in the planar experiment: the tracker measurement, the
% reward view term, and live views use the marker camera's x-z geometry
% (vertical FOV and optical-axis tilt), derived from its calibration.
co = landing2d.config.defaultCommonObservationConfig(v2.scenario.padHeight);
[cameraFov,cameraPitchOffset] = landing2d.sensing.planarCameraGeometry(co.camera);
v2.sensor = struct( ...
    'fov',cameraFov,'maxRange',50,'bearingNoiseStd',deg2rad(0.15), ...
    'relativePositionNoiseStd',0.02,'confidenceFloor',0.05, ...
    'reacquisitionGateSigma',4,'processAccelerationStd',1.5, ...
    'initialPositionStd',2,'initialVelocityStd',3, ...
    'initialAccelerationStd',2,'accelerationDecayTime',1.5, ...
    ... % 100-Hz alpha-beta-gamma gains; keep 2-cm noise out of v/a states.
    'positionInnovationGain',0.20,'velocityInnovationGain',0.02, ...
    'accelerationInnovationGain',0.00005,'maxAccelerationEstimate',3.0, ...
    'predictionHorizon',0.5,'cameraPitchOffset',cameraPitchOffset);
v2.sensor.perturbation = struct('cleanProbability',0.50, ...
    'shortDropoutProbability',0.25,'shortDropoutDuration',[0.2,0.5], ...
    'sustainedDropoutDuration',[3.5,5.0], ...
    'pitchEventProbability',0.25,'pitchDuration',[0.15,0.4], ...
    'pitchRateAmplitude',deg2rad(2));

v2.safety = struct( ...
    'recentTrackGrace',0.5,'prolongedLoss',3.0, ...
    'minimumTrackConfidence',0.25,'touchdownHeight',0.04, ...
    'touchdownPositionTolerance',0.5,'touchdownSpeedX',0.35, ...
    'touchdownSpeedZ',0.30,'touchdownPitchTolerance',deg2rad(5), ...
    'touchdownPitchRateTolerance',deg2rad(10), ...
    'ceilingHeight',25,'minimumHeight',0,'abortHoldHeight',1.0, ...
    'abortVerticalSpeedTolerance',0.10,'responseDelay',0.15, ...
    'backupDurationLimit',8.0);

% Common reward of every compared method (reward_v4, docs/refactor/REWARD_RATIONALE.md).
% Planar camera-consistent shaping: the goal cost measures the horizontal error
% from the camera aim point h*tan(30 deg) ahead of the drone (goalCameraAim),
% because the forward-down marker camera loses the pad when the drone flies
% over it at altitude, and the shaping potential adds UGV speed matching
% (velocityPotentialWeight, velocityLength). With reward_v2 (aim at e_x = 0,
% potentialWeight 2, no speed term) plain PPO never tracked the accelerating
% UGV and landed 0% of nominal validation episodes in 2500 iterations. The
% terminal rewards, running-cost weights and readiness term are unchanged.
% The 3D option restores reward_v2 (landing2d.config.applySpatialDimension).
v2.reward = struct( ...
    'referenceTime',70,'discountTimeConstant',70, ...
    'goalLengthX',3,'goalLengthH',4,'goalHorizontalShare',0.65, ...
    'goalWeight',2.0,'viewWeight',1.0,'controlWeight',0.25, ...
    'readinessWeight',8.0,'readinessHeight',1.0, ...
    'potentialWeight',4.0,'goalCameraAim',true, ...
    'velocityPotentialWeight',4.0,'velocityLength',1.0, ...
    'approachPositionRate',0.35,'targetRelativeSpeed',1.0, ...
    'verticalPotentialWeight',4.0,'verticalSpeedLength',0.5, ...
    'targetDescentSpeed',0.4,'verticalPositionRate',0.8, ...
    'SUCCESS',25,'SAFE_ABORT',-15,'TASK_TIMEOUT',-12, ...
    'UNSAFE_CONTACT',-40,'UNAUTHORIZED_CONTACT',-40, ...
    'MISSED_PAD_CONTACT',-40,'SAFETY_ENVELOPE_VIOLATION',-40);

v2.randomStreams = struct('scenarioOffset',0,'sensorOffset',1000000, ...
    'policyOffset',2000000);
v2.manifest = struct('trainSeeds',1:2000,'validationSeeds',2001:2200, ...
    'testSeeds',3001:3200,'stressSeeds',9001:9200);
% Keep split sizes in the versioned experiment contract so every entry
% point (training, checkpoint replay, and final GUI) builds the same
% training signature. trainEvaluate reduces these only in smoke mode.
v2.validationEpisodeCount = 100;
v2.testEpisodeCount = 100;
% Policy observation: the 24-D common observation o_t = [G;D;H] for every
% compared method. The context graph is built from the same o_t; the 26-D
% causal packet remains an environment-internal record (and the 3D policy input).
v2.observationSchema = landing2d.observation.vectorSchema(co);
v2.contextSchemaVersion = 'minimal_observation_rgat_v3';
% No backup controller rewrites a learned command, and no perception-based
% landing authorization or SAFE_ABORT guard changes the planar outcome.
% Contacts are classified only by the common mechanical touchdown limits.
v2.actionApplication = 'direct_policy_v1';
% Common observation settings: perception, the safety supervisor and landing
% authorization (see landing2d.config.defaultCommonObservationConfig).
v2.commonObservation = co;
end
