function registry = methodRegistry()
% METHODREGISTRY  Official comparison methods of the planar contract and seed plans.
% One definition for training, evaluation, checkpoints, legends and tables.
% method_id is separate from the internal stateRepresentation. context_flat is
% not an official method (its code path remains for ablations). Display order,
% colors and line styles are shared by every figure.
% Ablations are configurable by id (landing2d.config.applyMethod) but are not
% official methods, so training, evaluation and figures skip them unless asked:
% the relation-perturbed R-GAT repeats over graph seeds inside one id. It left
% the official comparison on 2026-10-08 (its training matched the ontology
% R-GAT up to the relation-only stage).
methods = struct( ...
    'id',{'ppo','onto_rgat_ppo'}, ...
    'label',{'일반 PPO','온톨로지-RGAT PPO'}, ...
    'representation',{'baseline','context_rgat'}, ...
    'graphPerturbation',{'none','none'}, ...
    'color',{[0.10 0.32 0.62],[0.35 0.16 0.60]}, ...
    'lineStyle',{'-','-'}, ...
    'marker',{'o','s'});
ablations = struct( ...
    'id',{'shuffled_rgat_ppo'}, ...
    'label',{'관계 교란 RGAT PPO'}, ...
    'representation',{'context_rgat'}, ...
    'graphPerturbation',{'edge_relation_shuffle'}, ...
    'color',{[0.85 0.33 0.10]}, ...
    'lineStyle',{'--'}, ...
    'marker',{'^'});
% Sample-size plan (not a statistical sufficiency guarantee): training seeds
% for the preliminary and main studies, graph seeds for the perturbed ablation.
registry = struct('version','comparison_registry_v2','methods',methods, ...
    'ablations',ablations,'trainSeeds',struct('preliminary',1:5,'main',1:10), ...
    'graphSeeds',1:3);
end
