function validatePrimaryConfig(c)
% VALIDATEPRIMARYCONFIG  Units/ranges/version checks for planar_visibility_v2.
e=c.experiment; d=e.dynamics; s=e.scenario; sensor=e.sensor; safety=e.safety;
validateattributes(e.physicsDt,{'numeric'},{'scalar','positive','finite'});
validateattributes(e.policyDt,{'numeric'},{'scalar','positive','finite'});
assert(abs(e.policyDt/e.physicsDt-round(e.policyDt/e.physicsDt))<1e-10, ...
    'landing2d:TimingContract','policyDt must be a multiple of physicsDt.');
positiveDynamics={'mass','gravity','pitchLimit','pitchRateLimit', ...
    'pitchNaturalFrequency','pitchDampingRatio','thrustTimeConstant', ...
    'maxThrustWeightRatio'};
for i=1:numel(positiveDynamics)
    validateattributes(d.(positiveDynamics{i}),{'numeric'}, ...
        {'scalar','positive','finite'},mfilename,positiveDynamics{i});
end
ranges={'v1Range','a2Range','T1Range','T2Range','T3Range','heightRange'};
for i=1:numel(ranges)
    value=s.(ranges{i});
    validateattributes(value,{'numeric'},{'vector','numel',2,'real','finite'});
    assert(value(1)<=value(2),'landing2d:ScenarioRange','%s is not increasing.',ranges{i});
end
assert(s.v1Range(1)>0 && s.a2Range(1)>=0 && s.T1Range(1)>0 ...
    && s.T2Range(1)>0 && s.T3Range(1)>0 && s.heightRange(1)>0, ...
    'landing2d:ScenarioRange','Scenario ranges violate positive-domain rules.');
assert(c.axMax>s.a2Range(2), ...
    'landing2d:HorizontalAuthority', ...
    'axMax must exceed the maximum UGV acceleration for tracking margin.');
assert(sum([s.T1Range(2),s.T2Range(2),s.T3Range(2)])<=e.maxMissionTime, ...
    'landing2d:MissionDuration','Scenario range can exceed mission limit.');
assert(sensor.fov>0 && sensor.fov<pi && sensor.maxRange>0);
gains=[sensor.positionInnovationGain,sensor.velocityInnovationGain, ...
    sensor.accelerationInnovationGain];
assert(all(gains>0 & gains<=1) && sensor.maxAccelerationEstimate>0, ...
    'landing2d:EstimatorGain','Estimator gains/limits are invalid.');
p=sensor.perturbation;
assert(p.cleanProbability>=0 && p.shortDropoutProbability>=0 ...
    && p.cleanProbability+p.shortDropoutProbability<=1);
assert(safety.recentTrackGrace>0 && safety.prolongedLoss>safety.recentTrackGrace);
assert(safety.touchdownPitchTolerance<d.pitchLimit);
schema=e.observationSchema;
assert(schema.dimension==numel(schema.names) && ...
    numel(unique(schema.names))==schema.dimension, ...
    'landing2d:ObservationSchema','Observation fields must be unique and complete.');
assert(c.rl.observationDim==schema.dimension && ...
    c.rl.actionDim==numel(landing2d.environment.actionLimits(c)));
if landing2d.environment.isSpatial(c)
    validateSpatial(c);
end
if isfield(e,'commonObservation')
    validateCommonObservation(c);
end
if isfield(c,'consistency')
    validateConsistency(c);
end
allSeeds=[e.manifest.trainSeeds,e.manifest.validationSeeds, ...
    e.manifest.testSeeds,e.manifest.stressSeeds];
assert(numel(unique(allSeeds))==numel(allSeeds), ...
    'landing2d:ManifestOverlap','Scenario seed splits overlap.');
validateattributes(e.validationEpisodeCount,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(e.testEpisodeCount,{'numeric'}, ...
    {'scalar','integer','positive'});
assert(e.validationEpisodeCount<=numel(e.manifest.validationSeeds) ...
    && e.testEpisodeCount<=numel(e.manifest.testSeeds), ...
    'landing2d:ManifestCount','Evaluation count exceeds its manifest split.');
r=e.reward;
assert(r.potentialWeight>=0 && isfinite(r.potentialWeight), ...
    'landing2d:RewardPotential','potentialWeight must be finite and nonnegative.');
assert(r.readinessWeight>0 && isfinite(r.readinessWeight) ...
    && r.readinessHeight>0 && isfinite(r.readinessHeight), ...
    'landing2d:RewardReadiness','Landing-readiness reward settings are invalid.');
assert(r.goalHorizontalShare>0 && r.goalHorizontalShare<1, ...
    'landing2d:RewardGoalShare','goalHorizontalShare must be in (0,1).');
% Planar reward_v4 shaping terms (absent in the 3D option).
if isfield(r,'goalCameraAim')
    assert(islogical(r.goalCameraAim) && isscalar(r.goalCameraAim), ...
        'landing2d:RewardCameraAim','goalCameraAim must be a logical scalar.');
end
if isfield(r,'velocityPotentialWeight')
    assert(isfield(r,'velocityLength') && r.velocityLength>0 && isfinite(r.velocityLength) ...
        && r.velocityPotentialWeight>=0 && isfinite(r.velocityPotentialWeight), ...
        'landing2d:RewardVelocityPotential', ...
        'velocityPotentialWeight must be finite and nonnegative with a positive velocityLength.');
    if isfield(r,'approachPositionRate')
        assert(r.approachPositionRate>0 && isfinite(r.approachPositionRate) ...
            && isfield(r,'targetRelativeSpeed') && r.targetRelativeSpeed>0 ...
            && isfinite(r.targetRelativeSpeed), ...
            'landing2d:RewardApproachManifold', ...
            'Approach-manifold rate and target speed must be positive and finite.');
    end
end
if isfield(r,'verticalPotentialWeight')
    assert(r.verticalPotentialWeight>=0 && isfinite(r.verticalPotentialWeight) ...
        && r.verticalSpeedLength>0 && isfinite(r.verticalSpeedLength) ...
        && r.targetDescentSpeed>0 && isfinite(r.targetDescentSpeed) ...
        && r.verticalPositionRate>0 && isfinite(r.verticalPositionRate), ...
        'landing2d:RewardVerticalPotential', ...
        'Vertical approach potential settings must be positive and finite.');
end
assert(r.SUCCESS>r.TASK_TIMEOUT && r.TASK_TIMEOUT>r.SAFE_ABORT ...
    && r.SAFE_ABORT>r.UNSAFE_CONTACT, ...
    'landing2d:RewardOrdering','Terminal bonuses have the wrong order.');
assert(c.rl.unsafePenaltyCurriculumStart<r.SAFE_ABORT ...
    && c.rl.unsafePenaltyCurriculumStart>=r.UNSAFE_CONTACT, ...
    'landing2d:RewardCurriculum', ...
    'Training unsafe penalty must remain below SAFE_ABORT and above nominal unsafe.');
end

function validateSpatial(c)
% 3차원 확장 계약: 측방 패드 크기·가속도 권한·UGV 측방 운동 범위.
sp=c.experiment.spatial; s=c.experiment.scenario;
assert(strcmp(sp.schemaVersion,'spatial_visibility_v1'), ...
    'landing2d:ExperimentVersion','Unknown spatial experiment version.');
validateattributes(sp.padHalfWidth,{'numeric'},{'scalar','positive','finite'}, ...
    mfilename,'padHalfWidth');
validateattributes(sp.lateralAccelerationLimit,{'numeric'}, ...
    {'scalar','positive','finite'},mfilename,'lateralAccelerationLimit');
for name={'lateralV1Range','lateralA2Range'}
    value=s.(name{1});
    validateattributes(value,{'numeric'},{'vector','numel',2,'real','finite'}, ...
        mfilename,name{1});
    assert(value(1)<=value(2),'landing2d:ScenarioRange','%s is not increasing.',name{1});
end
validateattributes(s.y0,{'numeric'},{'scalar','real','finite'},mfilename,'y0');
assert(sp.lateralAccelerationLimit>max(abs(s.lateralA2Range)), ...
    'landing2d:LateralAuthority', ...
    'lateralAccelerationLimit must exceed the maximum UGV lateral acceleration.');
assert(sp.finalDescentHeight>c.experiment.safety.touchdownHeight ...
    && sp.finalDescentExitHeight>sp.finalDescentHeight ...
    && sp.finalDescentMaxDuration>0 ...
    && sp.finalDescentMaxDuration<=c.experiment.safety.prolongedLoss, ...
    'landing2d:FinalDescent', ...
    'Final descent needs touchdownHeight < enter < exit height and 0 < duration <= prolongedLoss.');
r=c.experiment.reward;
assert(isfield(r,'actionChangeWeight') && r.actionChangeWeight>=0 ...
    && isfinite(r.actionChangeWeight),'landing2d:RewardActionChange', ...
    'actionChangeWeight must be finite and nonnegative.');
assert(c.experiment.observationSchema.dimension==37 ...
    && strcmp(c.experiment.observationSchema.version,'causal_packet_v3_spatial'), ...
    'landing2d:ObservationSchema','3D option requires the 37-D spatial packet.');
end

function validateCommonObservation(c)
% 공통 관측 o_t와 부가 정보 Gamma: 마커 슬롯·패드 내 배치·카메라 보정·UGV 장착 관계·
% 상태추정기·시뮬레이션 검출기·측위 잡음·정규화.
co=c.experiment.commonObservation;
assert(strcmp(co.schemaVersion,'minimal_common_observation_v3'), ...
    'landing2d:CommonObservation','Unknown common observation version.');
ids=co.pad.markerIds; M=numel(ids);
assert(M>=1 && numel(unique(ids))==M && all(ids>=0 & ids==round(ids)), ...
    'landing2d:CommonObservation','Marker IDs must be unique nonnegative integers.');
validateattributes(co.pad.markerCenters,{'numeric'},{'size',[M,2],'real','finite'}, ...
    mfilename,'markerCenters');
validateattributes(co.pad.markerSides,{'numeric'},{'vector','numel',M,'positive','finite'}, ...
    mfilename,'markerSides');
extent=abs(co.pad.markerCenters)+0.5*co.pad.markerSides(:);
assert(all(extent(:)<=c.padHalfLength), ...
    'landing2d:CommonObservation','Every marker must lie on the landing pad.');
cam=co.camera; detector=co.detector;
assert(ischar(cam.calibrationId) && ~isempty(cam.calibrationId), ...
    'landing2d:CommonObservation','camera.calibrationId must identify the calibration.');
validateattributes(cam.imageSize,{'numeric'},{'vector','numel',2,'integer','>=',2}, ...
    mfilename,'imageSize');
assert(detector.pixelNoiseStd>=0 && detector.minimumSidePixels>0 ...
    && detector.borderPixels>=0 && 2*detector.borderPixels<min(cam.imageSize)-1, ...
    'landing2d:CommonObservation','Simulated detector settings are invalid.');
K=cam.intrinsicMatrix;
validateattributes(K,{'numeric'},{'size',[3,3],'real','finite'},mfilename,'intrinsicMatrix');
assert(K(1,1)>0 && K(2,2)>0 && isequal(K(2,1),K(3,1),K(3,2),0) && K(3,3)==1, ...
    'landing2d:CameraIntrinsics', ...
    'intrinsicMatrix must be [fx s cx; 0 fy cy; 0 0 1] with fx, fy > 0.');
validateattributes(cam.distortion,{'numeric'},{'vector','numel',5,'real','finite'}, ...
    mfilename,'distortion');
T=cam.bodyToCamera;
validateattributes(T,{'numeric'},{'size',[4,4],'real','finite'},mfilename,'bodyToCamera');
R=T(1:3,1:3);
assert(isequal(T(4,:),[0,0,0,1]) && norm(R'*R-eye(3))<1e-9 && abs(det(R)-1)<1e-9, ...
    'landing2d:CameraExtrinsics', ...
    'bodyToCamera must be a homogeneous SE(3) transform with a proper rotation.');
nav=co.navigation;
assert(nav.velocityNoiseStd>=0 && nav.attitudeNoiseStd>=0, ...
    'landing2d:CommonObservation','Navigation noise must be nonnegative.');
% 시간 기준 잡음표: 마커·측위·tracker 전용 난수열이 서로, 그리고 시나리오·외생 사건·
% 정책 난수열과 겹치지 않아야 합니다.
streams=co.randomStreams; base=c.experiment.randomStreams;
offsets=[streams.markerOffset,streams.navigationOffset,streams.trackerOffset, ...
    base.scenarioOffset,base.sensorOffset,base.policyOffset];
assert(strcmp(streams.indexing,'time_indexed_v1') && numel(unique(offsets))==numel(offsets), ...
    'landing2d:CommonObservation', ...
    'Common-observation noise needs time-indexed tables from distinct random streams.');
validateattributes(co.ugv.padOffset,{'numeric'},{'vector','numel',2,'real','finite'}, ...
    mfilename,'padOffset');
e=co.estimator;
fd=co.finalDescent; safety=c.experiment.safety;
assert(fd.enterHeight>safety.touchdownHeight && fd.exitHeight>fd.enterHeight ...
    && fd.maxDuration>0 && fd.maxDuration<=safety.prolongedLoss, ...
    'landing2d:FinalDescent', ...
    'Final descent needs touchdownHeight < enter < exit height and 0 < duration <= prolongedLoss.');
validateattributes(e.accelerationNoiseStd,{'numeric'},{'vector','numel',2,'positive','finite'}, ...
    mfilename,'accelerationNoiseStd');
assert(e.cornerNoiseStd>0 && e.attitudeNoiseStd>=0 ...
    && e.initialVelocityStd>0 && e.maxReprojectionError>0 ...
    && e.pnpIterations>=1 && e.pnpIterations==round(e.pnpIterations), ...
    'landing2d:CommonObservation','UGV estimator settings are invalid.');
n=co.normalization;
assert(all([n.relativePositionScale,n.heightScale,n.ageScale]>0), ...
    'landing2d:CommonObservation','Normalization scales must be positive.');
if ~landing2d.environment.isSpatial(c)
    % 평면 계약의 카메라는 하나: tracker 기하 = 마커 카메라 보정 (3차원은 하향 카메라 유지).
    [fov,offset]=landing2d.sensing.planarCameraGeometry(cam);
    sensor=c.experiment.sensor;
    assert(abs(sensor.fov-fov)<1e-12 && abs(sensor.cameraPitchOffset-offset)<1e-12, ...
        'landing2d:CameraGeometry', ...
        'The planar tracker camera must match the marker camera calibration.');
end
end

function validateConsistency(c)
% 정책 일관성 검증 설정 (평가 전용): 관측오차 배율·고정 probe·명령 로그.
cc=c.consistency;
assert(strcmp(cc.schemaVersion,'policy_consistency_v1'), ...
    'landing2d:Consistency','Unknown consistency configuration version.');
validateattributes(cc.noiseScales,{'numeric'},{'vector','real','finite','nonnegative'}, ...
    mfilename,'noiseScales');
assert(issorted(cc.noiseScales,'strictascend') && any(cc.noiseScales==cc.nominalScale) ...
    && any(cc.noiseScales==cc.referenceScale) && cc.nominalScale==1, ...
    'landing2d:Consistency', ...
    'noiseScales must increase and contain the reference and the nominal (1) scale.');
p=cc.probe;
assert(strcmp(p.driver,'causal_tracking_v1') && p.driverNoise>=0 && isfinite(p.driverNoise) ...
    && p.stride>=1 && p.stride==round(p.stride), ...
    'landing2d:Consistency','Probe driver settings are invalid.');
streams=c.experiment.randomStreams; used=[streams.scenarioOffset,streams.sensorOffset, ...
    streams.policyOffset];
if isfield(c.experiment,'commonObservation')
    co=c.experiment.commonObservation.randomStreams;
    used=[used,co.markerOffset,co.navigationOffset,co.trackerOffset];
end
assert(~ismember(p.randomOffset,used),'landing2d:Consistency', ...
    'The probe driver needs its own random stream.');
e=c.experiment;
assert(p.validationEpisodeCount>=1 && p.validationEpisodeCount<=numel(e.manifest.validationSeeds) ...
    && p.testEpisodeCount>=1 && p.testEpisodeCount<=numel(e.manifest.testSeeds), ...
    'landing2d:Consistency','Probe episode counts exceed their manifest split.');
validateattributes(cc.log.physicsSteps,{'logical','numeric'},{'scalar','binary'}, ...
    mfilename,'log.physicsSteps');
validateattributes(cc.trainingSnapshots,{'numeric'},{'scalar','integer','nonnegative'}, ...
    mfilename,'trainingSnapshots');
v=cc.validity;
assert(issorted(v.horizonCandidates,'strictascend') && all(v.horizonCandidates>0) ...
    && v.gridPoints>=3 && v.gridPoints==round(v.gridPoints) ...
    && v.minimumApplicable>0 && v.minimumApplicable<=1 && v.minimumContextSamples>=1 ...
    && v.minimumDriverValid>0 && v.minimumDriverValid<=1 ...
    && issorted(v.kappaCandidates,'strictascend') && all(v.kappaCandidates>=0), ...
    'landing2d:Consistency','Validity judge settings are invalid.');
j=cc.jerk;
assert(j.initialTransient>=0 && j.settling>=0 && j.minimumWindow>0, ...
    'landing2d:Consistency','Steady-window settings are invalid.');
end
