function validatePrimaryConfig(c)
% VALIDATEPRIMARYCONFIG  Units/ranges/version checks for planar_visibility_v2.
e=c.experiment; d=e.dynamics; s=e.scenario; sensor=e.sensor; safety=e.safety;
validateattributes(e.physicsDt,{'numeric'},{'scalar','positive','finite'});
validateattributes(e.policyDt,{'numeric'},{'scalar','positive','finite'});
assert(abs(e.policyDt/e.physicsDt-round(e.policyDt/e.physicsDt))<1e-10, ...
    'landing2d:TimingContract','policyDt must be a multiple of physicsDt.');
positiveDynamics={'mass','gravity','pitchLimit','pitchRateLimit', ...
    'pitchNaturalFrequency','pitchDampingRatio','thrustTimeConstant', ...
    'maxThrustWeightRatio'};
for i=1:numel(positiveDynamics)
    validateattributes(d.(positiveDynamics{i}),{'numeric'}, ...
        {'scalar','positive','finite'},mfilename,positiveDynamics{i});
end
ranges={'v1Range','a2Range','T1Range','T2Range','T3Range','heightRange'};
for i=1:numel(ranges)
    value=s.(ranges{i});
    validateattributes(value,{'numeric'},{'vector','numel',2,'real','finite'});
    assert(value(1)<=value(2),'landing2d:ScenarioRange','%s is not increasing.',ranges{i});
end
assert(s.v1Range(1)>0 && s.a2Range(1)>=0 && s.T1Range(1)>0 ...
    && s.T2Range(1)>0 && s.T3Range(1)>0 && s.heightRange(1)>0, ...
    'landing2d:ScenarioRange','Scenario ranges violate positive-domain rules.');
assert(c.axMax>s.a2Range(2), ...
    'landing2d:HorizontalAuthority', ...
    'axMax must exceed the maximum UGV acceleration for tracking margin.');
assert(sum([s.T1Range(2),s.T2Range(2),s.T3Range(2)])<=e.maxMissionTime, ...
    'landing2d:MissionDuration','Scenario range can exceed mission limit.');
assert(sensor.fov>0 && sensor.fov<pi && sensor.maxRange>0);
gains=[sensor.positionInnovationGain,sensor.velocityInnovationGain, ...
    sensor.accelerationInnovationGain];
assert(all(gains>0 & gains<=1) && sensor.maxAccelerationEstimate>0, ...
    'landing2d:EstimatorGain','Estimator gains/limits are invalid.');
p=sensor.perturbation;
assert(p.cleanProbability>=0 && p.shortDropoutProbability>=0 ...
    && p.cleanProbability+p.shortDropoutProbability<=1);
assert(safety.recentTrackGrace>0 && safety.prolongedLoss>safety.recentTrackGrace);
assert(safety.touchdownPitchTolerance<d.pitchLimit);
schema=e.observationSchema;
assert(schema.dimension==numel(schema.names) && ...
    numel(unique(schema.names))==schema.dimension, ...
    'landing2d:ObservationSchema','Observation fields must be unique and complete.');
assert(c.rl.observationDim==schema.dimension && ...
    c.rl.actionDim==numel(landing2d.environment.actionLimits(c)));
if landing2d.environment.isSpatial(c)
    validateSpatial(c);
end
allSeeds=[e.manifest.trainSeeds,e.manifest.validationSeeds, ...
    e.manifest.testSeeds,e.manifest.stressSeeds];
assert(numel(unique(allSeeds))==numel(allSeeds), ...
    'landing2d:ManifestOverlap','Scenario seed splits overlap.');
validateattributes(e.validationEpisodeCount,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(e.testEpisodeCount,{'numeric'}, ...
    {'scalar','integer','positive'});
assert(e.validationEpisodeCount<=numel(e.manifest.validationSeeds) ...
    && e.testEpisodeCount<=numel(e.manifest.testSeeds), ...
    'landing2d:ManifestCount','Evaluation count exceeds its manifest split.');
r=e.reward;
assert(r.potentialWeight>=0 && isfinite(r.potentialWeight), ...
    'landing2d:RewardPotential','potentialWeight must be finite and nonnegative.');
assert(r.readinessWeight>0 && isfinite(r.readinessWeight) ...
    && r.readinessHeight>0 && isfinite(r.readinessHeight), ...
    'landing2d:RewardReadiness','Landing-readiness reward settings are invalid.');
assert(r.goalHorizontalShare>0 && r.goalHorizontalShare<1, ...
    'landing2d:RewardGoalShare','goalHorizontalShare must be in (0,1).');
assert(r.SUCCESS>r.TASK_TIMEOUT && r.TASK_TIMEOUT>r.SAFE_ABORT ...
    && r.SAFE_ABORT>r.UNSAFE_CONTACT, ...
    'landing2d:RewardOrdering','Terminal bonuses have the wrong order.');
assert(c.rl.unsafePenaltyCurriculumStart<r.SAFE_ABORT ...
    && c.rl.unsafePenaltyCurriculumStart>=r.UNSAFE_CONTACT, ...
    'landing2d:RewardCurriculum', ...
    'Training unsafe penalty must remain below SAFE_ABORT and above nominal unsafe.');
end

function validateSpatial(c)
% 3차원 확장 계약: 측방 패드 크기·가속도 권한·UGV 측방 운동 범위.
sp=c.experiment.spatial; s=c.experiment.scenario;
assert(strcmp(sp.schemaVersion,'spatial_visibility_v1'), ...
    'landing2d:ExperimentVersion','Unknown spatial experiment version.');
validateattributes(sp.padHalfWidth,{'numeric'},{'scalar','positive','finite'}, ...
    mfilename,'padHalfWidth');
validateattributes(sp.lateralAccelerationLimit,{'numeric'}, ...
    {'scalar','positive','finite'},mfilename,'lateralAccelerationLimit');
for name={'lateralV1Range','lateralA2Range'}
    value=s.(name{1});
    validateattributes(value,{'numeric'},{'vector','numel',2,'real','finite'}, ...
        mfilename,name{1});
    assert(value(1)<=value(2),'landing2d:ScenarioRange','%s is not increasing.',name{1});
end
validateattributes(s.y0,{'numeric'},{'scalar','real','finite'},mfilename,'y0');
assert(sp.lateralAccelerationLimit>max(abs(s.lateralA2Range)), ...
    'landing2d:LateralAuthority', ...
    'lateralAccelerationLimit must exceed the maximum UGV lateral acceleration.');
assert(sp.finalDescentHeight>c.experiment.safety.touchdownHeight ...
    && sp.finalDescentExitHeight>sp.finalDescentHeight ...
    && sp.finalDescentMaxDuration>0 ...
    && sp.finalDescentMaxDuration<=c.experiment.safety.prolongedLoss, ...
    'landing2d:FinalDescent', ...
    'Final descent needs touchdownHeight < enter < exit height and 0 < duration <= prolongedLoss.');
r=c.experiment.reward;
assert(isfield(r,'actionChangeWeight') && r.actionChangeWeight>=0 ...
    && isfinite(r.actionChangeWeight),'landing2d:RewardActionChange', ...
    'actionChangeWeight must be finite and nonnegative.');
assert(c.experiment.observationSchema.dimension==37 ...
    && strcmp(c.experiment.observationSchema.version,'causal_packet_v3_spatial'), ...
    'landing2d:ObservationSchema','3D option requires the 37-D spatial packet.');
end
