function track = initialPadTrack(sensor)
% INITIALPADTRACK  Uncertain prior; deliberately contains no hidden pad truth.
track = struct('initialized',false,'padX',0,'padVx',0,'padAx',0, ...
    'positionStd',sensor.initialPositionStd, ...
    'velocityStd',sensor.initialVelocityStd, ...
    'accelerationStd',sensor.initialAccelerationStd, ...
    'lastUpdateTime',NaN,'lastMeasurementTime',NaN, ...
    'lastMeasurementPadX',NaN,'lastMeasuredVelocity',NaN, ...
    'lastVelocityTime',NaN,'timeSinceLastDetection',Inf, ...
    'lastConfidence',0,'lastBearing',0,'bearingValid',false);
end
