function G = staticContext(c)
% STATICCONTEXT  공통 관측의 부가 정보 Gamma.
%   Gamma = {K, d, BT_C, 마커 구성·기하, UGV 장착 관계, 추정기 설정, 좌표계·정규화·이력 설정}
% 공통 인지 전처리(PnP·UGV 상태추정·정규화)와 이후 그래프 생성기가 참조하는 고정 설정이며,
% 매 시점 관측 벡터에는 넣지 않습니다. 기준 강화학습과 온톨로지–R-GAT 모델에
% 같은 Gamma를 제공합니다. 시뮬레이션 검출기·측위 잡음(co.detector, co.navigation)과
% 난수열은 센서 모델 내부 정보라 포함하지 않습니다.
co = c.experiment.commonObservation;
cam = co.camera;
camera = struct( ...
    'calibrationId',cam.calibrationId, ...
    'imageSize',cam.imageSize, ...
    'intrinsicMatrix',cam.intrinsicMatrix, ...
    'distortionModel','plumb_bob', ...
    'distortion',cam.distortion, ...
    'bodyToCamera',cam.bodyToCamera, ...
    'pixelOrigin','zero-based');
pad = struct( ...
    'padId',co.pad.padId, ...
    'markerIds',co.pad.markerIds(:)', ...     % 순서 = 고정 슬롯
    'markerSides',co.pad.markerSides(:)', ...
    'markerCenters',co.pad.markerCenters, ...
    'markerCorners',landing2d.sensing.markerGeometry(co.pad), ...
    'cornerOrder',{{'TL','TR','BR','BL'}});
ugv = struct( ...
    'padOffset',co.ugv.padOffset(:), ...      % r_{G->P} [x; z]
    'referencePoint','ground point below the pad center', ...
    'attitude','level straight-line driving: R_WG = I, pitch = pitch rate = 0');
estimator = co.estimator;
estimator.model = 'planar marker-board PnP -> local UGV position -> constant-velocity Kalman filter';
frames = struct( ...
    'local',struct('frameId','local','axes','x travel, y left, z up (planar y = 0)', ...
        'unit','m','origin','x: scenario start, z: ground'), ...
    'body',struct('frameId','body','axes','x forward, y left, z thrust axis', ...
        'attitude','R_WB = R_y(theta), observed as [sin(theta), cos(theta)]'), ...
    'camera',struct('frameId','camera_optical', ...
        'axes','x image right, y image down, z optical axis'), ...
    'pad',struct('frameId','pad','axes','x forward, y left, z deck normal', ...
        'origin','deck surface center (landing target)'), ...
    'ugv',struct('frameId','ugv','axes','x forward, z up', ...
        'origin','ground point below the pad center'));
history = struct('length',1, ...
    'content','previous-decision UGV and drone position/velocity', ...
    'reset','episode start');
n = co.normalization;
normalization = struct('relativePosition',n.relativePositionScale, ...
    'height',n.heightScale,'vx',c.vxMax,'vz',c.vzMax, ...
    'pitchRate',c.experiment.dynamics.pitchRateLimit,'age',n.ageScale, ...
    'rule',['x: (x-x_D)/(|x-x_D|+s) with the current drone x_D; z, v: x/(|x|+s); ' ...
        'age t/(t+s), never updated = 1']);
G = struct('version',co.schemaVersion,'camera',camera,'pad',pad,'ugv',ugv, ...
    'estimator',estimator,'frames',frames,'history',history, ...
    'normalization',normalization);
end
