function assertSameProblem(baselineCfg,proposedCfg)
% ASSERTSAMEPROBLEM  두 설정이 상태 표현만 다른지 실행 중에 확인.
%
% 제안 모델이 기준 모델과 같은 문제를 푸는지 보장하는 점검입니다. 보상 함수와
% 계수, 행동 정의와 한계, 환경 동역학, 종료 조건, PPO 알고리즘 설정, 학습
% 일정, 시드, 평가 시나리오가 하나라도 다르면 여기서 멈춥니다.
%
% 실험 변수는 cfg.graphState.stateRepresentation 하나여야 합니다.

% ---- 보상 (요구사항 4번: r_t_proposed == r_t_baseline)
reward = {'captureWeight','distanceWeight','captureMode','distanceMode', ...
    'distanceRateShare','distanceRateScale','distanceScale','distanceExponent'};
compare(baselineCfg.rl,proposedCfg.rl,reward,'reward');

% ---- 행동 공간 (요구사항 5번)
compare(baselineCfg.rl,proposedCfg.rl,{'actionDim','actionInterval'},'action');
compare(baselineCfg,proposedCfg,{'axMax','azMax','vxMax','vzMax'},'action limit');

% ---- 환경과 종료 조건
environment = {'dt','tEnd','segmentTimes','scenarioSpeeds','ugvAccelMax', ...
    'padHeight','padHalfLength','initialHeight','maxHeight','ceilingHeight', ...
    'cameraFovDeg','reacquireInnerRatio','reacquireHoldTime', ...
    'touchdownHeight','touchdownSpeedX','touchdownSpeedZ','controller'};
compare(baselineCfg,proposedCfg,environment,'environment');

% ---- PPO 알고리즘과 학습 일정
ppo = {'seed','hiddenSize','observationDim','ppoIterations', ...
    'episodesPerIteration','ppoEpochs','miniBatch','clipRatio','gamma', ...
    'lambda','policyLearnRate','valueLearnRate','entropyWeight', ...
    'initialLogStd','maxGradNorm','valueWarmup','evaluateEvery', ...
    'useBehaviorClone','bcEpisodes','bcEpochs','bcBatch','bcLearnRate', ...
    'initialHeightRange','initialOffsetRange','initialSpeedRange', ...
    'initialOffsetFraction','curriculumFraction','curriculumStartHeight', ...
    'teacherHeightRange','teacherNoise'};
compare(baselineCfg.rl,proposedCfg.rl,ppo,'PPO');

% ---- 기준 모델 쪽이 실제로 기준 상태 표현인지
assert(strcmp(baselineCfg.graphState.stateRepresentation,'baseline'), ...
    'landing2d:BaselineStateChanged', ...
    'The baseline arm must keep stateRepresentation = baseline.');

% ---- 제안 모델은 옛 보상 설계 경로를 쓰지 않아야 함 (요구사항 19번)
assert(~isfield(proposedCfg,'ontologyRewardApplied') ...
    || ~proposedCfg.ontologyRewardApplied, ...
    'landing2d:LegacyRewardInProposedPath', ...
    ['The proposed arm must run with the legacy ontology reward design ' ...
     'disabled. landing2d.ontology.applyDesign must not touch this config.']);
end

function compare(a,b,fields,label)
for i = 1:numel(fields)
    key = fields{i};
    assert(isfield(a,key) && isfield(b,key), ...
        'landing2d:MissingSetting','Missing %s setting: %s',label,key);
    assert(isequal(a.(key),b.(key)), ...
        'landing2d:ProblemMismatch', ...
        ['The proposed model must keep the baseline %s unchanged, but %s ' ...
         'differs. Only graphState.stateRepresentation may change.'], ...
        label,key);
end
end
