function [schema,T] = contextSchema(mode)
% CONTEXTSCHEMA  Compact typed ontology used by planar_visibility_v2.
if nargin < 1, mode = 'context_rgat'; end
semantic = {'PadVisibility','PadMotion','DroneTranslation','DroneAttitude', ...
    'RelativeTracking','TrackingCorrection','ViewRecovery', ...
    'DescentEligibility','LandingInhibit'};
queries = {'PolicyNode','ValueNode'};
schema.nodeNames = [semantic,queries];
schema.nNodes = numel(schema.nodeNames);
schema.ontologyNodes = 1:numel(semantic);
schema.policyNode = 10; schema.valueNode = 11;
schema.decisionNodes = [10,11];
schema.nodeClasses = {'ObservationState','MotionEstimate','OwnState', ...
    'OwnState','RelativeState','DecisionContext','DecisionContext', ...
    'DecisionContext','DecisionContext','ReadoutQuery','ReadoutQuery'};
schema.relationNames = {'informs','affects_visibility','supports', ...
    'inhibits','contributes','self'};
schema.nRelations = numel(schema.relationNames);
edges = { ...
    'PadMotion','RelativeTracking','informs'; ...
    'DroneTranslation','RelativeTracking','informs'; ...
    'DroneAttitude','PadVisibility','affects_visibility'; ...
    'DroneTranslation','PadVisibility','affects_visibility'; ...
    'PadMotion','TrackingCorrection','informs'; ...
    'RelativeTracking','TrackingCorrection','informs'; ...
    'PadVisibility','ViewRecovery','informs'; ...
    'DroneAttitude','ViewRecovery','informs'; ...
    'RelativeTracking','ViewRecovery','informs'; ...
    'PadVisibility','DescentEligibility','supports'; ...
    'RelativeTracking','DescentEligibility','informs'; ...
    'DroneTranslation','DescentEligibility','informs'; ...
    'DroneAttitude','DescentEligibility','informs'; ...
    'PadVisibility','LandingInhibit','informs'; ...
    'RelativeTracking','LandingInhibit','informs'; ...
    'DroneTranslation','LandingInhibit','informs'; ...
    'LandingInhibit','DescentEligibility','inhibits'};
src = zeros(1,size(edges,1)); dst = src; rel = src;
for i = 1:size(edges,1)
    src(i) = find(strcmp(schema.nodeNames,edges{i,1}));
    dst(i) = find(strcmp(schema.nodeNames,edges{i,2}));
    rel(i) = find(strcmp(schema.relationNames,edges{i,3}));
end
contributes = find(strcmp(schema.relationNames,'contributes'));
self = find(strcmp(schema.relationNames,'self'));
for node = schema.ontologyNodes
    src = [src,node,node]; %#ok<AGROW>
    dst = [dst,schema.policyNode,schema.valueNode]; %#ok<AGROW>
    rel = [rel,contributes,contributes]; %#ok<AGROW>
end
src = [src,1:schema.nNodes];
dst = [dst,1:schema.nNodes];
rel = [rel,self*ones(1,schema.nNodes)];
if strcmp(mode,'context_gat')
    rel(:) = 1;
    schema.relationNames = {'adjacent'};
    schema.nRelations = 1;
elseif ~ismember(mode,{'context_rgat','context_flat','context_node_pool'})
    error('landing2d:ContextMode','Unknown context graph mode %s.',mode);
end
schema.src = src; schema.dst = dst; schema.rel = rel;
schema.featureNames = {'primary','signedPrimary','secondary', ...
    'signedSecondary','validity','confidence','uncertainty','trend', ...
    'urgency','remainingTime','bias','typeId'};
schema.inDim = numel(schema.featureNames);
schema.neutralValue = zeros(1,schema.nNodes);
schema.riskNodes = [7,9];
schema.goalNode = 8;
schema.variant = 'compact_context_graph_v2';
schema.edgeTable = edges;
schema.provenance = featureProvenance();
if nargout > 1, T = landing2d.rgat.topology(schema); end
end

function p = featureProvenance()
p = struct( ...
    'PadVisibility','packet visibility measurements and predicted bearing', ...
    'PadMotion','shared causal pad track estimate and uncertainty', ...
    'DroneTranslation','synchronized own h/vx/vz', ...
    'DroneAttitude','synchronized own sin/cos pitch and pitch rate', ...
    'RelativeTracking','estimated signed ex/relative vx and uncertainty', ...
    'TrackingCorrection','bounded signed correction context from relative estimates', ...
    'ViewRecovery','predicted bearing/FOV margin and detection age', ...
    'DescentEligibility','bounded causal alignment/confidence/braking evidence', ...
    'LandingInhibit','public inhibit/abort flags and causal uncertainty');
end
