function validateGraphStateConfig(gs)
% VALIDATEGRAPHSTATECONFIG  상태 표현 설정 검증.
modes = {'baseline','semantic_flat','node_pool','gat','ontology_rgat', ...
    'context_flat','context_node_pool','context_gat','context_rgat'};
assert(ischar(gs.stateRepresentation) && isrow(gs.stateRepresentation) ...
    && ismember(gs.stateRepresentation,modes), ...
    'landing2d:UnknownStateRepresentation', ...
    'graphState.stateRepresentation must be one of: %s.',strjoin(modes,', '));
assert(ischar(gs.readout) && isrow(gs.readout) ...
    && ismember(gs.readout,{'decision_nodes','meanmax','mean','grouped', ...
    'raw_plus_groups'}), ...
    'landing2d:UnknownReadout', ...
    'graphState.readout must be decision_nodes, meanmax, or mean.');
positiveInteger = {'hiddenDim','relationDim','graphDim'};
for i = 1:numel(positiveInteger)
    validateattributes(gs.(positiveInteger{i}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,positiveInteger{i});
end
positive = {'initScale','encoderLearnRate','positionScale','distanceScale', ...
    'alignScale','speedScale','searchScale','padSpeedScale'};
for i = 1:numel(positive)
    validateattributes(gs.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(gs.useScratchSettings,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'useScratchSettings');
validateattributes(gs.freezeStaticBackbone,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'freezeStaticBackbone');
validateattributes(gs.graphAdaptationWarmupFraction,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<',1}, ...
    mfilename,'graphAdaptationWarmupFraction');
validateattributes(gs.preserveRawPolicyDuringGraphAdaptation, ...
    {'logical','numeric'},{'scalar','real','finite','binary'}, ...
    mfilename,'preserveRawPolicyDuringGraphAdaptation');
validateattributes(gs.graphSelectionMargin,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename,'graphSelectionMargin');
assert(isstruct(gs.pretrain) && isscalar(gs.pretrain), ...
    'graphState.pretrain must be a scalar struct.');
validateattributes(gs.pretrain.enabled,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'pretrain.enabled');
for name = {'episodes','maxDecisions','epochs','batchSize'}
    validateattributes(gs.pretrain.(name{1}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,name{1});
end
validateattributes(gs.pretrain.seedOffset,{'numeric'}, ...
    {'scalar','real','finite','nonnegative','integer'},mfilename,'seedOffset');
validateattributes(gs.pretrain.maskProbability,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<',1},mfilename,'pretrain.maskProbability');
validateattributes(gs.pretrain.learnRate,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'pretrain.learnRate');
assert(ischar(gs.policyFile) && isrow(gs.policyFile) ...
    && ~isempty(strtrim(gs.policyFile)), ...
    'graphState.policyFile must be a nonempty character vector.');
end
