function validateGraphStateConfig(gs)
% VALIDATEGRAPHSTATECONFIG  상태 표현 설정 검증.
modes = {'baseline','node_pool','gat','ontology_rgat'};
assert(ischar(gs.stateRepresentation) && isrow(gs.stateRepresentation) ...
    && ismember(gs.stateRepresentation,modes), ...
    'landing2d:UnknownStateRepresentation', ...
    'graphState.stateRepresentation must be one of: %s.',strjoin(modes,', '));
assert(ischar(gs.readout) && isrow(gs.readout) ...
    && ismember(gs.readout,{'meanmax','mean'}), ...
    'landing2d:UnknownReadout','graphState.readout must be meanmax or mean.');
positiveInteger = {'hiddenDim','relationDim','graphDim'};
for i = 1:numel(positiveInteger)
    validateattributes(gs.(positiveInteger{i}),{'numeric'}, ...
        {'scalar','real','finite','positive','integer'},mfilename,positiveInteger{i});
end
positive = {'initScale','encoderLearnRate','positionScale','distanceScale', ...
    'alignScale','speedScale','searchScale','padSpeedScale'};
for i = 1:numel(positive)
    validateattributes(gs.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(gs.useScratchSettings,{'logical','numeric'}, ...
    {'scalar','real','finite','binary'},mfilename,'useScratchSettings');
assert(ischar(gs.policyFile) && isrow(gs.policyFile) ...
    && ~isempty(strtrim(gs.policyFile)), ...
    'graphState.policyFile must be a nonempty character vector.');
end
