function v2 = defaultPlanarVisibilityConfig()
% DEFAULTPLANARVISIBILITYCONFIG  Versioned contract for the primary experiment.
% Values are simulation starting points, not identified vehicle parameters.
v2.schemaVersion = 'planar_visibility_v2';
v2.enabled = true;
v2.legacyDynamics = false;
v2.physicsDt = 0.01;
v2.policyDt = 0.10;
v2.maxMissionTime = 70;

v2.dynamics = struct( ...
    'mass',1.5,'gravity',9.81, ...
    'pitchLimit',deg2rad(20),'pitchRateLimit',deg2rad(90), ...
    'pitchNaturalFrequency',10,'pitchDampingRatio',1, ...
    'thrustTimeConstant',0.05,'maxThrustWeightRatio',1.6, ...
    'pitchDisturbanceLimit',deg2rad(2));

v2.scenario = struct( ...
    'parameterization','duration','v1Range',[0.5,2.5], ...
    'a2Range',[0.3,1.5],'T1Range',[0.5,4], ...
    'T2Range',[0.5,4],'T3Range',[15,55], ...
    'heightRange',[4,8],'x0',0,'padHeight',0.6, ...
    'sustainedDroneSpeed',10,'speedMargin',0.5, ...
    'baseSeed',20261002,'maxRejections',1000);

v2.sensor = struct( ...
    'fov',deg2rad(50),'maxRange',50,'bearingNoiseStd',deg2rad(0.15), ...
    'relativePositionNoiseStd',0.02,'confidenceFloor',0.05, ...
    'reacquisitionGateSigma',4,'processAccelerationStd',1.5, ...
    'initialPositionStd',2,'initialVelocityStd',3, ...
    'initialAccelerationStd',2,'accelerationDecayTime',1.5, ...
    ... % 100-Hz alpha-beta-gamma gains; keep 2-cm noise out of v/a states.
    'positionInnovationGain',0.20,'velocityInnovationGain',0.02, ...
    'accelerationInnovationGain',0.00005,'maxAccelerationEstimate',3.0, ...
    'predictionHorizon',0.5,'cameraPitchOffset',0);
v2.sensor.perturbation = struct('cleanProbability',0.50, ...
    'shortDropoutProbability',0.25,'shortDropoutDuration',[0.2,0.5], ...
    'sustainedDropoutDuration',[3.5,5.0], ...
    'pitchEventProbability',0.25,'pitchDuration',[0.15,0.4], ...
    'pitchRateAmplitude',deg2rad(2));

v2.safety = struct( ...
    'recentTrackGrace',0.5,'prolongedLoss',3.0, ...
    'minimumTrackConfidence',0.25,'touchdownHeight',0.04, ...
    'touchdownPositionTolerance',0.5,'touchdownSpeedX',0.35, ...
    'touchdownSpeedZ',0.30,'touchdownPitchTolerance',deg2rad(5), ...
    'touchdownPitchRateTolerance',deg2rad(10), ...
    'ceilingHeight',25,'minimumHeight',0,'abortHoldHeight',1.0, ...
    'abortVerticalSpeedTolerance',0.10,'responseDelay',0.15, ...
    'backupDurationLimit',8.0);

v2.reward = struct( ...
    'referenceTime',70,'discountTimeConstant',70, ...
    'goalLengthX',3,'goalLengthH',4,'goalHorizontalShare',0.65, ...
    'goalWeight',2.0,'viewWeight',1.0,'controlWeight',0.25, ...
    'readinessWeight',8.0,'readinessHeight',1.0, ...
    'potentialWeight',2.0, ...
    'SUCCESS',25,'SAFE_ABORT',-15,'TASK_TIMEOUT',-12, ...
    'UNSAFE_CONTACT',-40,'UNAUTHORIZED_CONTACT',-40, ...
    'MISSED_PAD_CONTACT',-40,'SAFETY_ENVELOPE_VIOLATION',-40);

v2.randomStreams = struct('scenarioOffset',0,'sensorOffset',1000000, ...
    'policyOffset',2000000);
v2.manifest = struct('trainSeeds',1:2000,'validationSeeds',2001:2200, ...
    'testSeeds',3001:3200,'stressSeeds',9001:9200);
% Keep split sizes in the versioned experiment contract so every entry
% point (training, checkpoint replay, and final GUI) builds the same
% training signature. run_planar_visibility reduces these only in smoke mode.
v2.validationEpisodeCount = 100;
v2.testEpisodeCount = 100;
v2.observationSchema = landing2d.sensing.observationSchema();
v2.contextSchemaVersion = 'compact_context_graph_v3_grouped';
end
