function validatePrimaryConfig(c)
% VALIDATEPRIMARYCONFIG  Units/ranges/version checks for planar_visibility_v2.
e=c.experiment; d=e.dynamics; s=e.scenario; sensor=e.sensor; safety=e.safety;
validateattributes(e.physicsDt,{'numeric'},{'scalar','positive','finite'});
validateattributes(e.policyDt,{'numeric'},{'scalar','positive','finite'});
assert(abs(e.policyDt/e.physicsDt-round(e.policyDt/e.physicsDt))<1e-10, ...
    'landing2d:TimingContract','policyDt must be a multiple of physicsDt.');
positiveDynamics={'mass','gravity','pitchLimit','pitchRateLimit', ...
    'pitchNaturalFrequency','pitchDampingRatio','thrustTimeConstant', ...
    'maxThrustWeightRatio'};
for i=1:numel(positiveDynamics)
    validateattributes(d.(positiveDynamics{i}),{'numeric'}, ...
        {'scalar','positive','finite'},mfilename,positiveDynamics{i});
end
ranges={'v1Range','a2Range','T1Range','T2Range','T3Range','heightRange'};
for i=1:numel(ranges)
    value=s.(ranges{i});
    validateattributes(value,{'numeric'},{'vector','numel',2,'real','finite'});
    assert(value(1)<=value(2),'landing2d:ScenarioRange','%s is not increasing.',ranges{i});
end
assert(s.v1Range(1)>0 && s.a2Range(1)>=0 && s.T1Range(1)>0 ...
    && s.T2Range(1)>0 && s.T3Range(1)>0 && s.heightRange(1)>0, ...
    'landing2d:ScenarioRange','Scenario ranges violate positive-domain rules.');
assert(sum([s.T1Range(2),s.T2Range(2),s.T3Range(2)])<=e.maxMissionTime, ...
    'landing2d:MissionDuration','Scenario range can exceed mission limit.');
assert(sensor.fov>0 && sensor.fov<pi && sensor.maxRange>0);
gains=[sensor.positionInnovationGain,sensor.velocityInnovationGain, ...
    sensor.accelerationInnovationGain];
assert(all(gains>0 & gains<=1) && sensor.maxAccelerationEstimate>0, ...
    'landing2d:EstimatorGain','Estimator gains/limits are invalid.');
p=sensor.perturbation;
assert(p.cleanProbability>=0 && p.shortDropoutProbability>=0 ...
    && p.cleanProbability+p.shortDropoutProbability<=1);
assert(safety.recentTrackGrace>0 && safety.prolongedLoss>safety.recentTrackGrace);
assert(safety.touchdownPitchTolerance<d.pitchLimit);
schema=e.observationSchema;
assert(schema.dimension==numel(schema.names) && ...
    numel(unique(schema.names))==schema.dimension, ...
    'landing2d:ObservationSchema','Observation fields must be unique and complete.');
assert(c.rl.observationDim==schema.dimension && c.rl.actionDim==2);
allSeeds=[e.manifest.trainSeeds,e.manifest.validationSeeds, ...
    e.manifest.testSeeds,e.manifest.stressSeeds];
assert(numel(unique(allSeeds))==numel(allSeeds), ...
    'landing2d:ManifestOverlap','Scenario seed splits overlap.');
r=e.reward;
assert(r.potentialWeight>=0 && isfinite(r.potentialWeight), ...
    'landing2d:RewardPotential','potentialWeight must be finite and nonnegative.');
assert(r.readinessWeight>0 && isfinite(r.readinessWeight) ...
    && r.readinessHeight>0 && isfinite(r.readinessHeight), ...
    'landing2d:RewardReadiness','Landing-readiness reward settings are invalid.');
assert(r.SUCCESS>r.SAFE_ABORT && r.SAFE_ABORT>r.TASK_TIMEOUT ...
    && r.TASK_TIMEOUT>r.UNSAFE_CONTACT, ...
    'landing2d:RewardOrdering','Terminal bonuses have the wrong order.');
assert(c.rl.unsafePenaltyCurriculumStart<r.SAFE_ABORT ...
    && c.rl.unsafePenaltyCurriculumStart>=r.UNSAFE_CONTACT, ...
    'landing2d:RewardCurriculum', ...
    'Training unsafe penalty must remain below SAFE_ABORT and above nominal unsafe.');
end
