function validateConfig(c)
positive = {'dt','tEnd','ugvAccelMax','padHeight','padHalfLength', ...
    'pnGain','pnApproachSpeed','pnApproachGain','pnClosingGain', ...
    'pnSpeedMatchGain','pnRecoveryGain','pnVerticalGain','pnHeightGain', ...
    'pnMinClosing','pnMinRange', ...
    'initialHeight','maxHeight','kpX','kdX','kpZ','kdZ','axMax','azMax', ...
    'vxMax','vzMax','climbSpeed','descentSpeed','nearPadDescentGain', ...
    'alignPositionTol','alignSpeedTol','reacquireHoldTime', ...
    'touchdownHeight','touchdownSpeedX','touchdownSpeedZ','animationHz', ...
    'figureResolution'};
for i = 1:numel(positive)
    validateattributes(c.(positive{i}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename,positive{i});
end
validateattributes(c.scenarioSpeeds,{'numeric'}, ...
    {'2d','real','finite','nonnegative','nonempty'},mfilename,'scenarioSpeeds');
assert(size(c.scenarioSpeeds,2)==3,'scenarioSpeeds must have three columns.');
assert(c.dt < c.tEnd,'dt must be smaller than tEnd.');
flags = {'animate','makeFinalPlots','saveResults','makeDetailPlots','makeTrajectoryPlots', ...
    'trajectoryFlightOnly','showSegmentLabels','showEventLines', ...
    'figureVisible','saveFig','showLiveDashboard'};
for i = 1:numel(flags)
    validateattributes(c.(flags{i}),{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,flags{i});
end
assert(numel(c.segmentTimes)==2 && all(isfinite(c.segmentTimes)) ...
    && c.segmentTimes(1)>0 && c.segmentTimes(1)<c.segmentTimes(2) ...
    && c.segmentTimes(2)<c.tEnd,'Require 0 < t1 < t2 < tEnd.');
assert(abs(c.tEnd/c.dt-round(c.tEnd/c.dt))<1e-7,'tEnd must be a multiple of dt.');
assert(isscalar(c.cameraFovDeg) && c.cameraFovDeg>0 && c.cameraFovDeg<170, ...
    'cameraFovDeg must be between 0 and 170.');
assert(isscalar(c.reacquireInnerRatio) && c.reacquireInnerRatio>0 ...
    && c.reacquireInnerRatio<1,'reacquireInnerRatio must be in (0,1).');
assert(c.initialHeight<=c.maxHeight,'initialHeight must not exceed maxHeight.');
assert(c.ceilingHeight>c.maxHeight, ...
    'ceilingHeight must be above maxHeight so the guidance law never reaches it.');
assert(c.touchdownHeight<c.initialHeight,'touchdownHeight must be below initialHeight.');
assert(c.climbSpeed<=c.vzMax && c.descentSpeed<=c.vzMax, ...
    'climbSpeed and descentSpeed must not exceed vzMax.');
assert(isscalar(c.playbackSpeed) && isnumeric(c.playbackSpeed) ...
    && isreal(c.playbackSpeed) && c.playbackSpeed>0,'playbackSpeed must be > 0 or Inf.');
validateattributes(c.segmentTimes,{'numeric'},{'vector','real','finite','numel',2});
validateattributes(c.cameraFovDeg,{'numeric'},{'scalar','real','finite'});
validateattributes(c.reacquireInnerRatio,{'numeric'},{'scalar','real','finite'});
validateattributes(c.segmentColors,{'numeric'}, ...
    {'real','finite','size',[3,3],'>=',0,'<=',1},mfilename,'segmentColors');
validateattributes(c.segmentAlpha,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<=',1},mfilename,'segmentAlpha');
validateattributes(c.evaluationMonteCarloRuns,{'numeric'}, ...
    {'scalar','real','finite','integer','>=',2},mfilename,'evaluationMonteCarloRuns');
validateattributes(c.evaluationMonteCarloSeed,{'numeric'}, ...
    {'scalar','real','finite','integer','nonnegative'},mfilename,'evaluationMonteCarloSeed');
evaluationRanges = {'evaluationHeightRange','evaluationOffsetRange', ...
    'evaluationSpeedRange'};
for i = 1:numel(evaluationRanges)
    value = c.(evaluationRanges{i});
    validateattributes(value,{'numeric'},{'vector','real','finite','numel',2}, ...
        mfilename,evaluationRanges{i});
    assert(value(1) <= value(2),'%s must be increasing.',evaluationRanges{i});
end
assert(c.evaluationHeightRange(1) > 0,'evaluationHeightRange must be positive.');
assert(ischar(c.controller) && isrow(c.controller) ...
    && ismember(lower(c.controller),{'pn','pd'}), ...
    'landing2d:UnknownController','controller must be pn or pd.');
assert(c.pnApproachSpeed <= c.vzMax, ...
    'pnApproachSpeed must not exceed vzMax.');
assert(ischar(c.outputDir) && isrow(c.outputDir) && ~isempty(strtrim(c.outputDir)), ...
    'outputDir must be a nonempty character vector or string scalar.');
% figureVisible=false와 animate=true는 서로 모순되므로 명확히 거부.
assert(c.figureVisible || ~c.animate, ...
    'Set animate=false when figureVisible=false.');
% 학습 설정은 비교 실행에서만 사용하므로 있을 때만 검증.
if isfield(c,'rl')
    landing2d.rl.validateRlConfig(c.rl);
end
if isfield(c,'ontology')
    landing2d.ontology.validateOntologyConfig(c.ontology);
end
if isfield(c,'graphState')
    landing2d.graphstate.validateGraphStateConfig(c.graphState);
end
if isfield(c,'useLegacyOntologyReward')
    validateattributes(c.useLegacyOntologyReward,{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,'useLegacyOntologyReward');
end
if isfield(c,'scratchBaseline')
    validateattributes(c.scratchBaseline,{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,'scratchBaseline');
end
if isfield(c,'showOntologyTab')
    validateattributes(c.showOntologyTab,{'logical','numeric'}, ...
        {'scalar','real','finite','binary'},mfilename,'showOntologyTab');
end
if isfield(c,'ontologyViewSource')
    assert((ischar(c.ontologyViewSource) && isrow(c.ontologyViewSource)) ...
        || (isstring(c.ontologyViewSource) && isscalar(c.ontologyViewSource)), ...
        'landing2d:OntologyViewSource', ...
        'ontologyViewSource must be a character vector or string scalar.');
end

end
